// @generated by scripts/generate-playwright-protocol.mjs from
// rust/protocol/playwright/*.yml. Do not edit by hand.

#![allow(clippy::all, missing_docs, unused_imports)]

use serde::{Deserialize, Serialize};

use super::*;
use crate::playwright::connection::{
    Binary, Channel, ChannelType, ObjectRef, ProtocolError, ProtocolEvent, Ref,
};

/// `APIResponse` object from `api.yml`.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct APIResponse {
    #[serde(rename = "fetchUid")]
    pub fetch_uid: String,
    #[serde(rename = "url")]
    pub url: String,
    #[serde(rename = "status")]
    pub status: i64,
    #[serde(rename = "statusText")]
    pub status_text: String,
    #[serde(rename = "headers")]
    pub headers: Vec<NameValue>,
    #[serde(rename = "securityDetails", default, skip_serializing_if = "Option::is_none")]
    pub security_details: Option<SecurityDetails>,
    #[serde(rename = "serverAddr", default, skip_serializing_if = "Option::is_none")]
    pub server_addr: Option<RemoteAddr>,
    #[serde(rename = "timing", default, skip_serializing_if = "Option::is_none")]
    pub timing: Option<ResourceTiming>,
    #[serde(rename = "responseEndTiming", default, skip_serializing_if = "Option::is_none")]
    pub response_end_timing: Option<f64>,
}
