// @generated by scripts/generate-playwright-protocol.mjs from
// rust/protocol/playwright/*.yml. Do not edit by hand.

#![allow(clippy::all, missing_docs, unused_imports)]

use serde::{Deserialize, Serialize};

use super::*;
use crate::playwright::connection::{
    Binary, Channel, ChannelType, ObjectRef, ProtocolError, ProtocolEvent, Ref,
};

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct MetadataLocation {
    #[serde(rename = "file")]
    pub file: String,
    #[serde(rename = "line", default, skip_serializing_if = "Option::is_none")]
    pub line: Option<i64>,
    #[serde(rename = "column", default, skip_serializing_if = "Option::is_none")]
    pub column: Option<i64>,
}

/// `Metadata` object from `core.yml`.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct Metadata {
    #[serde(rename = "location", default, skip_serializing_if = "Option::is_none")]
    pub location: Option<MetadataLocation>,
    #[serde(rename = "title", default, skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    #[serde(rename = "internal", default, skip_serializing_if = "Option::is_none")]
    pub internal: Option<bool>,
    #[serde(rename = "stepId", default, skip_serializing_if = "Option::is_none")]
    pub step_id: Option<String>,
    #[serde(rename = "timeout", default, skip_serializing_if = "Option::is_none")]
    pub timeout: Option<f64>,
}

/// `ClientSideCallMetadata` object from `core.yml`.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct ClientSideCallMetadata {
    #[serde(rename = "id")]
    pub id: i64,
    #[serde(rename = "stack", default, skip_serializing_if = "Option::is_none")]
    pub stack: Option<Vec<StackFrame>>,
}

/// `SDKLanguage` enum from `core.yml`.
#[derive(Debug, Clone, Copy, Default, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum SDKLanguage {
    #[default]
    #[serde(rename = "javascript")]
    Javascript,
    #[serde(rename = "python")]
    Python,
    #[serde(rename = "java")]
    Java,
    #[serde(rename = "csharp")]
    Csharp,
}

#[derive(Debug, Clone, Copy, Default, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum WaitInfoPhase {
    #[default]
    #[serde(rename = "before")]
    Before,
    #[serde(rename = "after")]
    After,
    #[serde(rename = "log")]
    Log,
}

/// `WaitInfo` object from `core.yml`.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct WaitInfo {
    #[serde(rename = "waitId")]
    pub wait_id: String,
    #[serde(rename = "phase")]
    pub phase: WaitInfoPhase,
    #[serde(rename = "event", default, skip_serializing_if = "Option::is_none")]
    pub event: Option<String>,
    #[serde(rename = "message", default, skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
    #[serde(rename = "error", default, skip_serializing_if = "Option::is_none")]
    pub error: Option<String>,
}
