// @generated by scripts/generate-playwright-protocol.mjs from
// rust/protocol/playwright/*.yml. Do not edit by hand.

#![allow(clippy::all, missing_docs, unused_imports)]

use serde::{Deserialize, Serialize};

use super::*;
use crate::playwright::connection::{
    Binary, Channel, ChannelType, ObjectRef, ProtocolError, ProtocolEvent, Ref,
};

/// Initializer the driver sends when it creates a `Electron`.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct ElectronInitializer {}

#[derive(Debug, Clone, Copy, Default, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum ElectronLaunchParamsAcceptDownloads {
    #[default]
    #[serde(rename = "accept")]
    Accept,
    #[serde(rename = "deny")]
    Deny,
    #[serde(rename = "internal-browser-default")]
    InternalBrowserDefault,
}

#[derive(Debug, Clone, Copy, Default, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum ElectronLaunchParamsColorScheme {
    #[default]
    #[serde(rename = "dark")]
    Dark,
    #[serde(rename = "light")]
    Light,
    #[serde(rename = "no-preference")]
    NoPreference,
    #[serde(rename = "no-override")]
    NoOverride,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct ElectronLaunchParamsGeolocation {
    #[serde(rename = "longitude")]
    pub longitude: f64,
    #[serde(rename = "latitude")]
    pub latitude: f64,
    #[serde(rename = "accuracy", default, skip_serializing_if = "Option::is_none")]
    pub accuracy: Option<f64>,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct ElectronLaunchParamsRecordVideoSize {
    #[serde(rename = "width")]
    pub width: i64,
    #[serde(rename = "height")]
    pub height: i64,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct ElectronLaunchParamsRecordVideoShowActions {
    /// Properties of the `ShowActionsOptions` mixin.
    #[serde(flatten)]
    pub show_actions_options: ShowActionsOptions,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct ElectronLaunchParamsRecordVideo {
    #[serde(rename = "dir", default, skip_serializing_if = "Option::is_none")]
    pub dir: Option<String>,
    #[serde(rename = "size", default, skip_serializing_if = "Option::is_none")]
    pub size: Option<ElectronLaunchParamsRecordVideoSize>,
    #[serde(rename = "showActions", default, skip_serializing_if = "Option::is_none")]
    pub show_actions: Option<ElectronLaunchParamsRecordVideoShowActions>,
}

/// Parameters of `Electron.launch` (Launch electron).
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct ElectronLaunchParams {
    #[serde(rename = "executablePath", default, skip_serializing_if = "Option::is_none")]
    pub executable_path: Option<String>,
    #[serde(rename = "args", default, skip_serializing_if = "Option::is_none")]
    pub args: Option<Vec<String>>,
    #[serde(rename = "chromiumSandbox", default, skip_serializing_if = "Option::is_none")]
    pub chromium_sandbox: Option<bool>,
    #[serde(rename = "cwd", default, skip_serializing_if = "Option::is_none")]
    pub cwd: Option<String>,
    #[serde(rename = "env", default, skip_serializing_if = "Option::is_none")]
    pub env: Option<Vec<NameValue>>,
    #[serde(rename = "acceptDownloads", default, skip_serializing_if = "Option::is_none")]
    pub accept_downloads: Option<ElectronLaunchParamsAcceptDownloads>,
    #[serde(rename = "bypassCSP", default, skip_serializing_if = "Option::is_none")]
    pub bypass_csp: Option<bool>,
    #[serde(rename = "colorScheme", default, skip_serializing_if = "Option::is_none")]
    pub color_scheme: Option<ElectronLaunchParamsColorScheme>,
    #[serde(rename = "extraHTTPHeaders", default, skip_serializing_if = "Option::is_none")]
    pub extra_http_headers: Option<Vec<NameValue>>,
    #[serde(rename = "geolocation", default, skip_serializing_if = "Option::is_none")]
    pub geolocation: Option<ElectronLaunchParamsGeolocation>,
    #[serde(rename = "httpCredentials", default, skip_serializing_if = "Option::is_none")]
    pub http_credentials: Option<Vec<HttpCredentials>>,
    #[serde(rename = "ignoreHTTPSErrors", default, skip_serializing_if = "Option::is_none")]
    pub ignore_https_errors: Option<bool>,
    #[serde(rename = "locale", default, skip_serializing_if = "Option::is_none")]
    pub locale: Option<String>,
    #[serde(rename = "offline", default, skip_serializing_if = "Option::is_none")]
    pub offline: Option<bool>,
    #[serde(rename = "recordVideo", default, skip_serializing_if = "Option::is_none")]
    pub record_video: Option<ElectronLaunchParamsRecordVideo>,
    #[serde(rename = "strictSelectors", default, skip_serializing_if = "Option::is_none")]
    pub strict_selectors: Option<bool>,
    #[serde(rename = "timezoneId", default, skip_serializing_if = "Option::is_none")]
    pub timezone_id: Option<String>,
    #[serde(rename = "tracesDir", default, skip_serializing_if = "Option::is_none")]
    pub traces_dir: Option<String>,
    #[serde(rename = "artifactsDir", default, skip_serializing_if = "Option::is_none")]
    pub artifacts_dir: Option<String>,
    #[serde(rename = "selectorEngines", default, skip_serializing_if = "Option::is_none")]
    pub selector_engines: Option<Vec<SelectorEngine>>,
    #[serde(rename = "testIdAttributeName", default, skip_serializing_if = "Option::is_none")]
    pub test_id_attribute_name: Option<String>,
}

/// Result of `Electron.launch` (Launch electron).
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct ElectronLaunchResult {
    #[serde(rename = "electronApplication")]
    pub electron_application: Ref<ElectronApplication>,
}

/// Events a `Electron` channel can emit.
#[derive(Debug, Clone, PartialEq)]
pub enum ElectronEvent {
    /// An event this binding does not know (a newer driver).
    Unknown {
        /// Event name.
        method: String,
        /// Raw event parameters.
        params: serde_json::Value,
    },
}

impl ProtocolEvent for ElectronEvent {
    fn parse(method: &str, params: serde_json::Value) -> Result<Self, serde_json::Error> {
        match method {
            _ => Ok(Self::Unknown { method: method.to_string(), params }),
        }
    }
}

/// Channel for the `Electron` interface (`electron.yml`).
#[derive(Debug, Clone)]
pub struct Electron {
    channel: Channel,
}

impl ChannelType for Electron {
    const INTERFACE: &'static str = "Electron";
    type Initializer = ElectronInitializer;
    type Event = ElectronEvent;

    fn accepts(interface: &str) -> bool {
        matches!(interface, "Electron")
    }

    fn from_channel(channel: Channel) -> Self {
        Self { channel }
    }

    fn channel(&self) -> &Channel {
        &self.channel
    }
}

impl Electron {
    /// `Electron.launch` ("Launch electron").
    pub async fn launch(&self, params: ElectronLaunchParams) -> Result<ElectronLaunchResult, ProtocolError> {
        self.channel.send("launch", &params).await
    }
}
