// @generated by scripts/generate-playwright-protocol.mjs from
// rust/protocol/playwright/*.yml. Do not edit by hand.

#![allow(clippy::all, missing_docs, unused_imports)]

use serde::{Deserialize, Serialize};

use super::*;
use crate::playwright::connection::{
    Binary, Channel, ChannelType, ObjectRef, ProtocolError, ProtocolEvent, Ref,
};

/// Initializer the driver sends when it creates a `Frame`.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct FrameInitializer {
    #[serde(rename = "url")]
    pub url: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "parentFrame", default, skip_serializing_if = "Option::is_none")]
    pub parent_frame: Option<Ref<Frame>>,
    #[serde(rename = "loadStates")]
    pub load_states: Vec<LifecycleEvent>,
}

/// Parameters of `Frame.evalOnSelector` (Evaluate).
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct FrameEvalOnSelectorParams {
    #[serde(rename = "selector")]
    pub selector: String,
    #[serde(rename = "strict", default, skip_serializing_if = "Option::is_none")]
    pub strict: Option<bool>,
    #[serde(rename = "expression")]
    pub expression: String,
    #[serde(rename = "isFunction", default, skip_serializing_if = "Option::is_none")]
    pub is_function: Option<bool>,
    #[serde(rename = "arg")]
    pub arg: SerializedArgument,
}

/// Result of `Frame.evalOnSelector` (Evaluate).
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct FrameEvalOnSelectorResult {
    #[serde(rename = "value")]
    pub value: SerializedValue,
}

/// Parameters of `Frame.evalOnSelectorAll` (Evaluate).
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct FrameEvalOnSelectorAllParams {
    #[serde(rename = "selector")]
    pub selector: String,
    #[serde(rename = "expression")]
    pub expression: String,
    #[serde(rename = "isFunction", default, skip_serializing_if = "Option::is_none")]
    pub is_function: Option<bool>,
    #[serde(rename = "arg")]
    pub arg: SerializedArgument,
}

/// Result of `Frame.evalOnSelectorAll` (Evaluate).
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct FrameEvalOnSelectorAllResult {
    #[serde(rename = "value")]
    pub value: SerializedValue,
}

/// Parameters of `Frame.addScriptTag` (Add script tag).
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct FrameAddScriptTagParams {
    #[serde(rename = "url", default, skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
    #[serde(rename = "content", default, skip_serializing_if = "Option::is_none")]
    pub content: Option<String>,
    #[serde(rename = "type", default, skip_serializing_if = "Option::is_none")]
    pub r#type: Option<String>,
}

/// Result of `Frame.addScriptTag` (Add script tag).
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct FrameAddScriptTagResult {
    #[serde(rename = "element")]
    pub element: Ref<ElementHandle>,
}

/// Parameters of `Frame.addStyleTag` (Add style tag).
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct FrameAddStyleTagParams {
    #[serde(rename = "url", default, skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
    #[serde(rename = "content", default, skip_serializing_if = "Option::is_none")]
    pub content: Option<String>,
}

/// Result of `Frame.addStyleTag` (Add style tag).
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct FrameAddStyleTagResult {
    #[serde(rename = "element")]
    pub element: Ref<ElementHandle>,
}

#[derive(Debug, Clone, Copy, Default, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum FrameAriaSnapshotParamsMode {
    #[default]
    #[serde(rename = "ai")]
    Ai,
    #[serde(rename = "default")]
    Default,
}

/// Parameters of `Frame.ariaSnapshot` (Aria snapshot).
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct FrameAriaSnapshotParams {
    #[serde(rename = "mode", default, skip_serializing_if = "Option::is_none")]
    pub mode: Option<FrameAriaSnapshotParamsMode>,
    #[serde(rename = "selector", default, skip_serializing_if = "Option::is_none")]
    pub selector: Option<String>,
    #[serde(rename = "depth", default, skip_serializing_if = "Option::is_none")]
    pub depth: Option<i64>,
    #[serde(rename = "boxes", default, skip_serializing_if = "Option::is_none")]
    pub boxes: Option<bool>,
}

/// Result of `Frame.ariaSnapshot` (Aria snapshot).
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct FrameAriaSnapshotResult {
    #[serde(rename = "snapshot")]
    pub snapshot: String,
}

/// Parameters of `Frame.blur` (Blur).
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct FrameBlurParams {
    #[serde(rename = "selector")]
    pub selector: String,
    #[serde(rename = "strict", default, skip_serializing_if = "Option::is_none")]
    pub strict: Option<bool>,
}

#[derive(Debug, Clone, Copy, Default, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum FrameCheckParamsScroll {
    #[default]
    #[serde(rename = "auto")]
    Auto,
    #[serde(rename = "none")]
    None,
}

/// Parameters of `Frame.check` (Check).
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct FrameCheckParams {
    #[serde(rename = "selector")]
    pub selector: String,
    #[serde(rename = "strict", default, skip_serializing_if = "Option::is_none")]
    pub strict: Option<bool>,
    #[serde(rename = "force", default, skip_serializing_if = "Option::is_none")]
    pub force: Option<bool>,
    #[serde(rename = "scroll", default, skip_serializing_if = "Option::is_none")]
    pub scroll: Option<FrameCheckParamsScroll>,
    #[serde(rename = "position", default, skip_serializing_if = "Option::is_none")]
    pub position: Option<Point>,
    #[serde(rename = "trial", default, skip_serializing_if = "Option::is_none")]
    pub trial: Option<bool>,
}

#[derive(Debug, Clone, Copy, Default, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum FrameClickParamsScroll {
    #[default]
    #[serde(rename = "auto")]
    Auto,
    #[serde(rename = "none")]
    None,
}

#[derive(Debug, Clone, Copy, Default, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum FrameClickParamsModifiers {
    #[default]
    #[serde(rename = "Alt")]
    Alt,
    #[serde(rename = "Control")]
    Control,
    #[serde(rename = "ControlOrMeta")]
    ControlOrMeta,
    #[serde(rename = "Meta")]
    Meta,
    #[serde(rename = "Shift")]
    Shift,
}

#[derive(Debug, Clone, Copy, Default, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum FrameClickParamsButton {
    #[default]
    #[serde(rename = "left")]
    Left,
    #[serde(rename = "right")]
    Right,
    #[serde(rename = "middle")]
    Middle,
}

/// Parameters of `Frame.click` (Click).
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct FrameClickParams {
    #[serde(rename = "selector")]
    pub selector: String,
    #[serde(rename = "strict", default, skip_serializing_if = "Option::is_none")]
    pub strict: Option<bool>,
    #[serde(rename = "force", default, skip_serializing_if = "Option::is_none")]
    pub force: Option<bool>,
    #[serde(rename = "scroll", default, skip_serializing_if = "Option::is_none")]
    pub scroll: Option<FrameClickParamsScroll>,
    #[serde(rename = "noWaitAfter", default, skip_serializing_if = "Option::is_none")]
    pub no_wait_after: Option<bool>,
    #[serde(rename = "modifiers", default, skip_serializing_if = "Option::is_none")]
    pub modifiers: Option<Vec<FrameClickParamsModifiers>>,
    #[serde(rename = "position", default, skip_serializing_if = "Option::is_none")]
    pub position: Option<Point>,
    #[serde(rename = "delay", default, skip_serializing_if = "Option::is_none")]
    pub delay: Option<f64>,
    #[serde(rename = "button", default, skip_serializing_if = "Option::is_none")]
    pub button: Option<FrameClickParamsButton>,
    #[serde(rename = "clickCount", default, skip_serializing_if = "Option::is_none")]
    pub click_count: Option<i64>,
    #[serde(rename = "trial", default, skip_serializing_if = "Option::is_none")]
    pub trial: Option<bool>,
    #[serde(rename = "steps", default, skip_serializing_if = "Option::is_none")]
    pub steps: Option<i64>,
}

/// Result of `Frame.content` (Get content).
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct FrameContentResult {
    #[serde(rename = "value")]
    pub value: String,
}

#[derive(Debug, Clone, Copy, Default, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum FrameDragAndDropParamsScroll {
    #[default]
    #[serde(rename = "auto")]
    Auto,
    #[serde(rename = "none")]
    None,
}

/// Parameters of `Frame.dragAndDrop` (Drag and drop).
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct FrameDragAndDropParams {
    #[serde(rename = "source")]
    pub source: String,
    #[serde(rename = "target")]
    pub target: String,
    #[serde(rename = "force", default, skip_serializing_if = "Option::is_none")]
    pub force: Option<bool>,
    #[serde(rename = "scroll", default, skip_serializing_if = "Option::is_none")]
    pub scroll: Option<FrameDragAndDropParamsScroll>,
    #[serde(rename = "trial", default, skip_serializing_if = "Option::is_none")]
    pub trial: Option<bool>,
    #[serde(rename = "sourcePosition", default, skip_serializing_if = "Option::is_none")]
    pub source_position: Option<Point>,
    #[serde(rename = "targetPosition", default, skip_serializing_if = "Option::is_none")]
    pub target_position: Option<Point>,
    #[serde(rename = "strict", default, skip_serializing_if = "Option::is_none")]
    pub strict: Option<bool>,
    #[serde(rename = "steps", default, skip_serializing_if = "Option::is_none")]
    pub steps: Option<i64>,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct FrameDropParamsPayloads {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "mimeType", default, skip_serializing_if = "Option::is_none")]
    pub mime_type: Option<String>,
    #[serde(rename = "buffer")]
    pub buffer: Binary,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct FrameDropParamsData {
    #[serde(rename = "mimeType")]
    pub mime_type: String,
    #[serde(rename = "value")]
    pub value: String,
}

/// Parameters of `Frame.drop` (Drop files or data onto an element).
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct FrameDropParams {
    #[serde(rename = "selector")]
    pub selector: String,
    #[serde(rename = "strict", default, skip_serializing_if = "Option::is_none")]
    pub strict: Option<bool>,
    #[serde(rename = "position", default, skip_serializing_if = "Option::is_none")]
    pub position: Option<Point>,
    #[serde(rename = "payloads", default, skip_serializing_if = "Option::is_none")]
    pub payloads: Option<Vec<FrameDropParamsPayloads>>,
    #[serde(rename = "localPaths", default, skip_serializing_if = "Option::is_none")]
    pub local_paths: Option<Vec<String>>,
    #[serde(rename = "streams", default, skip_serializing_if = "Option::is_none")]
    pub streams: Option<Vec<Ref<WritableStream>>>,
    #[serde(rename = "data", default, skip_serializing_if = "Option::is_none")]
    pub data: Option<Vec<FrameDropParamsData>>,
}

#[derive(Debug, Clone, Copy, Default, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum FrameDblclickParamsScroll {
    #[default]
    #[serde(rename = "auto")]
    Auto,
    #[serde(rename = "none")]
    None,
}

#[derive(Debug, Clone, Copy, Default, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum FrameDblclickParamsModifiers {
    #[default]
    #[serde(rename = "Alt")]
    Alt,
    #[serde(rename = "Control")]
    Control,
    #[serde(rename = "ControlOrMeta")]
    ControlOrMeta,
    #[serde(rename = "Meta")]
    Meta,
    #[serde(rename = "Shift")]
    Shift,
}

#[derive(Debug, Clone, Copy, Default, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum FrameDblclickParamsButton {
    #[default]
    #[serde(rename = "left")]
    Left,
    #[serde(rename = "right")]
    Right,
    #[serde(rename = "middle")]
    Middle,
}

/// Parameters of `Frame.dblclick` (Double click).
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct FrameDblclickParams {
    #[serde(rename = "selector")]
    pub selector: String,
    #[serde(rename = "strict", default, skip_serializing_if = "Option::is_none")]
    pub strict: Option<bool>,
    #[serde(rename = "force", default, skip_serializing_if = "Option::is_none")]
    pub force: Option<bool>,
    #[serde(rename = "scroll", default, skip_serializing_if = "Option::is_none")]
    pub scroll: Option<FrameDblclickParamsScroll>,
    #[serde(rename = "modifiers", default, skip_serializing_if = "Option::is_none")]
    pub modifiers: Option<Vec<FrameDblclickParamsModifiers>>,
    #[serde(rename = "position", default, skip_serializing_if = "Option::is_none")]
    pub position: Option<Point>,
    #[serde(rename = "delay", default, skip_serializing_if = "Option::is_none")]
    pub delay: Option<f64>,
    #[serde(rename = "button", default, skip_serializing_if = "Option::is_none")]
    pub button: Option<FrameDblclickParamsButton>,
    #[serde(rename = "trial", default, skip_serializing_if = "Option::is_none")]
    pub trial: Option<bool>,
    #[serde(rename = "steps", default, skip_serializing_if = "Option::is_none")]
    pub steps: Option<i64>,
}

/// Parameters of `Frame.dispatchEvent` (Dispatch "{type}").
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct FrameDispatchEventParams {
    #[serde(rename = "selector")]
    pub selector: String,
    #[serde(rename = "strict", default, skip_serializing_if = "Option::is_none")]
    pub strict: Option<bool>,
    #[serde(rename = "type")]
    pub r#type: String,
    #[serde(rename = "eventInit")]
    pub event_init: SerializedArgument,
}

/// Parameters of `Frame.evaluateExpression` (Evaluate).
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct FrameEvaluateExpressionParams {
    #[serde(rename = "expression")]
    pub expression: String,
    #[serde(rename = "isFunction", default, skip_serializing_if = "Option::is_none")]
    pub is_function: Option<bool>,
    #[serde(rename = "arg")]
    pub arg: SerializedArgument,
}

/// Result of `Frame.evaluateExpression` (Evaluate).
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct FrameEvaluateExpressionResult {
    #[serde(rename = "value")]
    pub value: SerializedValue,
}

/// Parameters of `Frame.evaluateExpressionHandle` (Evaluate).
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct FrameEvaluateExpressionHandleParams {
    #[serde(rename = "expression")]
    pub expression: String,
    #[serde(rename = "isFunction", default, skip_serializing_if = "Option::is_none")]
    pub is_function: Option<bool>,
    #[serde(rename = "arg")]
    pub arg: SerializedArgument,
}

/// Result of `Frame.evaluateExpressionHandle` (Evaluate).
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct FrameEvaluateExpressionHandleResult {
    #[serde(rename = "handle")]
    pub handle: Ref<JSHandle>,
}

/// Parameters of `Frame.fill` (Fill "{value}").
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct FrameFillParams {
    #[serde(rename = "selector")]
    pub selector: String,
    #[serde(rename = "strict", default, skip_serializing_if = "Option::is_none")]
    pub strict: Option<bool>,
    #[serde(rename = "value")]
    pub value: String,
    #[serde(rename = "force", default, skip_serializing_if = "Option::is_none")]
    pub force: Option<bool>,
}

/// Parameters of `Frame.focus` (Focus).
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct FrameFocusParams {
    #[serde(rename = "selector")]
    pub selector: String,
    #[serde(rename = "strict", default, skip_serializing_if = "Option::is_none")]
    pub strict: Option<bool>,
}

/// Result of `Frame.frameElement` (Get frame element).
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct FrameFrameElementResult {
    #[serde(rename = "element")]
    pub element: Ref<ElementHandle>,
}

/// Parameters of `Frame.resolveSelector`.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct FrameResolveSelectorParams {
    #[serde(rename = "selector")]
    pub selector: String,
}

/// Result of `Frame.resolveSelector`.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct FrameResolveSelectorResult {
    #[serde(rename = "resolvedSelector")]
    pub resolved_selector: String,
}

/// Parameters of `Frame.highlight`.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct FrameHighlightParams {
    #[serde(rename = "selector")]
    pub selector: String,
    #[serde(rename = "style", default, skip_serializing_if = "Option::is_none")]
    pub style: Option<String>,
}

/// Parameters of `Frame.hideHighlight`.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct FrameHideHighlightParams {
    #[serde(rename = "selector")]
    pub selector: String,
}

/// Parameters of `Frame.getAttribute` (Get attribute "{name}").
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct FrameGetAttributeParams {
    #[serde(rename = "selector")]
    pub selector: String,
    #[serde(rename = "strict", default, skip_serializing_if = "Option::is_none")]
    pub strict: Option<bool>,
    #[serde(rename = "name")]
    pub name: String,
}

/// Result of `Frame.getAttribute` (Get attribute "{name}").
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct FrameGetAttributeResult {
    #[serde(rename = "value", default, skip_serializing_if = "Option::is_none")]
    pub value: Option<String>,
}

/// Parameters of `Frame.goto` (Navigate to "{url}").
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct FrameGotoParams {
    #[serde(rename = "url")]
    pub url: String,
    #[serde(rename = "waitUntil", default, skip_serializing_if = "Option::is_none")]
    pub wait_until: Option<LifecycleEvent>,
    #[serde(rename = "referer", default, skip_serializing_if = "Option::is_none")]
    pub referer: Option<String>,
}

/// Result of `Frame.goto` (Navigate to "{url}").
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct FrameGotoResult {
    #[serde(rename = "response", default, skip_serializing_if = "Option::is_none")]
    pub response: Option<Ref<Response>>,
}

#[derive(Debug, Clone, Copy, Default, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum FrameHoverParamsScroll {
    #[default]
    #[serde(rename = "auto")]
    Auto,
    #[serde(rename = "none")]
    None,
}

#[derive(Debug, Clone, Copy, Default, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum FrameHoverParamsModifiers {
    #[default]
    #[serde(rename = "Alt")]
    Alt,
    #[serde(rename = "Control")]
    Control,
    #[serde(rename = "ControlOrMeta")]
    ControlOrMeta,
    #[serde(rename = "Meta")]
    Meta,
    #[serde(rename = "Shift")]
    Shift,
}

/// Parameters of `Frame.hover` (Hover).
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct FrameHoverParams {
    #[serde(rename = "selector")]
    pub selector: String,
    #[serde(rename = "strict", default, skip_serializing_if = "Option::is_none")]
    pub strict: Option<bool>,
    #[serde(rename = "force", default, skip_serializing_if = "Option::is_none")]
    pub force: Option<bool>,
    #[serde(rename = "scroll", default, skip_serializing_if = "Option::is_none")]
    pub scroll: Option<FrameHoverParamsScroll>,
    #[serde(rename = "modifiers", default, skip_serializing_if = "Option::is_none")]
    pub modifiers: Option<Vec<FrameHoverParamsModifiers>>,
    #[serde(rename = "position", default, skip_serializing_if = "Option::is_none")]
    pub position: Option<Point>,
    #[serde(rename = "trial", default, skip_serializing_if = "Option::is_none")]
    pub trial: Option<bool>,
}

/// Parameters of `Frame.innerHTML` (Get HTML).
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct FrameInnerHTMLParams {
    #[serde(rename = "selector")]
    pub selector: String,
    #[serde(rename = "strict", default, skip_serializing_if = "Option::is_none")]
    pub strict: Option<bool>,
}

/// Result of `Frame.innerHTML` (Get HTML).
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct FrameInnerHTMLResult {
    #[serde(rename = "value")]
    pub value: String,
}

/// Parameters of `Frame.innerText` (Get inner text).
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct FrameInnerTextParams {
    #[serde(rename = "selector")]
    pub selector: String,
    #[serde(rename = "strict", default, skip_serializing_if = "Option::is_none")]
    pub strict: Option<bool>,
}

/// Result of `Frame.innerText` (Get inner text).
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct FrameInnerTextResult {
    #[serde(rename = "value")]
    pub value: String,
}

/// Parameters of `Frame.inputValue` (Get input value).
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct FrameInputValueParams {
    #[serde(rename = "selector")]
    pub selector: String,
    #[serde(rename = "strict", default, skip_serializing_if = "Option::is_none")]
    pub strict: Option<bool>,
}

/// Result of `Frame.inputValue` (Get input value).
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct FrameInputValueResult {
    #[serde(rename = "value")]
    pub value: String,
}

/// Parameters of `Frame.isChecked` (Is checked).
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct FrameIsCheckedParams {
    #[serde(rename = "selector")]
    pub selector: String,
    #[serde(rename = "strict", default, skip_serializing_if = "Option::is_none")]
    pub strict: Option<bool>,
}

/// Result of `Frame.isChecked` (Is checked).
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct FrameIsCheckedResult {
    #[serde(rename = "value")]
    pub value: bool,
}

/// Parameters of `Frame.isDisabled` (Is disabled).
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct FrameIsDisabledParams {
    #[serde(rename = "selector")]
    pub selector: String,
    #[serde(rename = "strict", default, skip_serializing_if = "Option::is_none")]
    pub strict: Option<bool>,
}

/// Result of `Frame.isDisabled` (Is disabled).
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct FrameIsDisabledResult {
    #[serde(rename = "value")]
    pub value: bool,
}

/// Parameters of `Frame.isEnabled` (Is enabled).
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct FrameIsEnabledParams {
    #[serde(rename = "selector")]
    pub selector: String,
    #[serde(rename = "strict", default, skip_serializing_if = "Option::is_none")]
    pub strict: Option<bool>,
}

/// Result of `Frame.isEnabled` (Is enabled).
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct FrameIsEnabledResult {
    #[serde(rename = "value")]
    pub value: bool,
}

/// Parameters of `Frame.isHidden` (Is hidden).
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct FrameIsHiddenParams {
    #[serde(rename = "selector")]
    pub selector: String,
    #[serde(rename = "strict", default, skip_serializing_if = "Option::is_none")]
    pub strict: Option<bool>,
}

/// Result of `Frame.isHidden` (Is hidden).
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct FrameIsHiddenResult {
    #[serde(rename = "value")]
    pub value: bool,
}

/// Parameters of `Frame.isVisible` (Is visible).
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct FrameIsVisibleParams {
    #[serde(rename = "selector")]
    pub selector: String,
    #[serde(rename = "strict", default, skip_serializing_if = "Option::is_none")]
    pub strict: Option<bool>,
}

/// Result of `Frame.isVisible` (Is visible).
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct FrameIsVisibleResult {
    #[serde(rename = "value")]
    pub value: bool,
}

/// Parameters of `Frame.isEditable` (Is editable).
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct FrameIsEditableParams {
    #[serde(rename = "selector")]
    pub selector: String,
    #[serde(rename = "strict", default, skip_serializing_if = "Option::is_none")]
    pub strict: Option<bool>,
}

/// Result of `Frame.isEditable` (Is editable).
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct FrameIsEditableResult {
    #[serde(rename = "value")]
    pub value: bool,
}

/// Parameters of `Frame.press` (Press "{key}").
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct FramePressParams {
    #[serde(rename = "selector")]
    pub selector: String,
    #[serde(rename = "strict", default, skip_serializing_if = "Option::is_none")]
    pub strict: Option<bool>,
    #[serde(rename = "key")]
    pub key: String,
    #[serde(rename = "delay", default, skip_serializing_if = "Option::is_none")]
    pub delay: Option<f64>,
    #[serde(rename = "noWaitAfter", default, skip_serializing_if = "Option::is_none")]
    pub no_wait_after: Option<bool>,
}

/// Parameters of `Frame.querySelector` (Query selector).
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct FrameQuerySelectorParams {
    #[serde(rename = "selector")]
    pub selector: String,
    #[serde(rename = "strict", default, skip_serializing_if = "Option::is_none")]
    pub strict: Option<bool>,
}

/// Result of `Frame.querySelector` (Query selector).
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct FrameQuerySelectorResult {
    #[serde(rename = "element", default, skip_serializing_if = "Option::is_none")]
    pub element: Option<Ref<ElementHandle>>,
}

/// Parameters of `Frame.querySelectorAll` (Query selector all).
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct FrameQuerySelectorAllParams {
    #[serde(rename = "selector")]
    pub selector: String,
}

/// Result of `Frame.querySelectorAll` (Query selector all).
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct FrameQuerySelectorAllResult {
    #[serde(rename = "elements")]
    pub elements: Vec<Ref<ElementHandle>>,
}

/// Parameters of `Frame.queryCount` (Query count).
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct FrameQueryCountParams {
    #[serde(rename = "selector")]
    pub selector: String,
}

/// Result of `Frame.queryCount` (Query count).
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct FrameQueryCountResult {
    #[serde(rename = "value")]
    pub value: i64,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct FrameSelectOptionParamsOptions {
    #[serde(rename = "valueOrLabel", default, skip_serializing_if = "Option::is_none")]
    pub value_or_label: Option<String>,
    #[serde(rename = "value", default, skip_serializing_if = "Option::is_none")]
    pub value: Option<String>,
    #[serde(rename = "label", default, skip_serializing_if = "Option::is_none")]
    pub label: Option<String>,
    #[serde(rename = "index", default, skip_serializing_if = "Option::is_none")]
    pub index: Option<i64>,
}

/// Parameters of `Frame.selectOption` (Select option).
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct FrameSelectOptionParams {
    #[serde(rename = "selector")]
    pub selector: String,
    #[serde(rename = "strict", default, skip_serializing_if = "Option::is_none")]
    pub strict: Option<bool>,
    #[serde(rename = "elements", default, skip_serializing_if = "Option::is_none")]
    pub elements: Option<Vec<Ref<ElementHandle>>>,
    #[serde(rename = "options", default, skip_serializing_if = "Option::is_none")]
    pub options: Option<Vec<FrameSelectOptionParamsOptions>>,
    #[serde(rename = "force", default, skip_serializing_if = "Option::is_none")]
    pub force: Option<bool>,
}

/// Result of `Frame.selectOption` (Select option).
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct FrameSelectOptionResult {
    #[serde(rename = "values")]
    pub values: Vec<String>,
}

/// Parameters of `Frame.setContent` (Set content).
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct FrameSetContentParams {
    #[serde(rename = "html")]
    pub html: String,
    #[serde(rename = "waitUntil", default, skip_serializing_if = "Option::is_none")]
    pub wait_until: Option<LifecycleEvent>,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct FrameSetInputFilesParamsPayloads {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "mimeType", default, skip_serializing_if = "Option::is_none")]
    pub mime_type: Option<String>,
    #[serde(rename = "buffer")]
    pub buffer: Binary,
}

/// Parameters of `Frame.setInputFiles` (Set input files).
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct FrameSetInputFilesParams {
    #[serde(rename = "selector")]
    pub selector: String,
    #[serde(rename = "strict", default, skip_serializing_if = "Option::is_none")]
    pub strict: Option<bool>,
    #[serde(rename = "payloads", default, skip_serializing_if = "Option::is_none")]
    pub payloads: Option<Vec<FrameSetInputFilesParamsPayloads>>,
    #[serde(rename = "localDirectory", default, skip_serializing_if = "Option::is_none")]
    pub local_directory: Option<String>,
    #[serde(rename = "directoryStream", default, skip_serializing_if = "Option::is_none")]
    pub directory_stream: Option<Ref<WritableStream>>,
    #[serde(rename = "localPaths", default, skip_serializing_if = "Option::is_none")]
    pub local_paths: Option<Vec<String>>,
    #[serde(rename = "streams", default, skip_serializing_if = "Option::is_none")]
    pub streams: Option<Vec<Ref<WritableStream>>>,
}

#[derive(Debug, Clone, Copy, Default, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum FrameTapParamsScroll {
    #[default]
    #[serde(rename = "auto")]
    Auto,
    #[serde(rename = "none")]
    None,
}

#[derive(Debug, Clone, Copy, Default, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum FrameTapParamsModifiers {
    #[default]
    #[serde(rename = "Alt")]
    Alt,
    #[serde(rename = "Control")]
    Control,
    #[serde(rename = "ControlOrMeta")]
    ControlOrMeta,
    #[serde(rename = "Meta")]
    Meta,
    #[serde(rename = "Shift")]
    Shift,
}

/// Parameters of `Frame.tap` (Tap).
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct FrameTapParams {
    #[serde(rename = "selector")]
    pub selector: String,
    #[serde(rename = "strict", default, skip_serializing_if = "Option::is_none")]
    pub strict: Option<bool>,
    #[serde(rename = "force", default, skip_serializing_if = "Option::is_none")]
    pub force: Option<bool>,
    #[serde(rename = "scroll", default, skip_serializing_if = "Option::is_none")]
    pub scroll: Option<FrameTapParamsScroll>,
    #[serde(rename = "modifiers", default, skip_serializing_if = "Option::is_none")]
    pub modifiers: Option<Vec<FrameTapParamsModifiers>>,
    #[serde(rename = "position", default, skip_serializing_if = "Option::is_none")]
    pub position: Option<Point>,
    #[serde(rename = "trial", default, skip_serializing_if = "Option::is_none")]
    pub trial: Option<bool>,
}

/// Parameters of `Frame.textContent` (Get text content).
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct FrameTextContentParams {
    #[serde(rename = "selector")]
    pub selector: String,
    #[serde(rename = "strict", default, skip_serializing_if = "Option::is_none")]
    pub strict: Option<bool>,
}

/// Result of `Frame.textContent` (Get text content).
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct FrameTextContentResult {
    #[serde(rename = "value", default, skip_serializing_if = "Option::is_none")]
    pub value: Option<String>,
}

/// Result of `Frame.title` (Get page title).
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct FrameTitleResult {
    #[serde(rename = "value")]
    pub value: String,
}

/// Parameters of `Frame.type` (Type "{text}").
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct FrameTypeParams {
    #[serde(rename = "selector")]
    pub selector: String,
    #[serde(rename = "strict", default, skip_serializing_if = "Option::is_none")]
    pub strict: Option<bool>,
    #[serde(rename = "text")]
    pub text: String,
    #[serde(rename = "delay", default, skip_serializing_if = "Option::is_none")]
    pub delay: Option<f64>,
}

#[derive(Debug, Clone, Copy, Default, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum FrameUncheckParamsScroll {
    #[default]
    #[serde(rename = "auto")]
    Auto,
    #[serde(rename = "none")]
    None,
}

/// Parameters of `Frame.uncheck` (Uncheck).
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct FrameUncheckParams {
    #[serde(rename = "selector")]
    pub selector: String,
    #[serde(rename = "strict", default, skip_serializing_if = "Option::is_none")]
    pub strict: Option<bool>,
    #[serde(rename = "force", default, skip_serializing_if = "Option::is_none")]
    pub force: Option<bool>,
    #[serde(rename = "scroll", default, skip_serializing_if = "Option::is_none")]
    pub scroll: Option<FrameUncheckParamsScroll>,
    #[serde(rename = "position", default, skip_serializing_if = "Option::is_none")]
    pub position: Option<Point>,
    #[serde(rename = "trial", default, skip_serializing_if = "Option::is_none")]
    pub trial: Option<bool>,
}

/// Parameters of `Frame.waitForTimeout` (Wait for timeout).
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct FrameWaitForTimeoutParams {
    #[serde(rename = "waitTimeout")]
    pub wait_timeout: f64,
}

