// @generated by scripts/generate-playwright-protocol.mjs from
// rust/protocol/playwright/*.yml. Do not edit by hand.

//! Typed Playwright protocol bindings generated from the vendored spec.
//!
//! 34 interfaces and 318 commands. Every interface is a
//! channel type with one `async fn` per command; see
//! [`crate::playwright::connection`] for the runtime they run on.

/// Playwright release the vendored protocol spec was taken from.
pub const PROTOCOL_VERSION: &str = "1.62.1";

mod android;
mod android_device;
mod android_socket;
mod android_types;
mod api_request_context;
mod api_types;
mod artifact;
mod binding_call;
mod browser;
mod browser_context;
mod browser_type;
mod cdp_session;
mod core_types;
mod debug_controller;
mod debugger;
mod dialog;
mod disposable;
mod electron;
mod electron_application;
mod element_handle;
mod frame;
mod frame_2;
mod js_handle;
mod json_pipe;
mod local_utils;
mod mixins_types;
mod network_types;
mod page;
mod page_2;
mod playwright;
mod playwright_types;
mod request;
mod response;
mod root;
mod route;
mod serialized_types;
mod socks_support;
mod stream;
mod structs_types;
mod tracing;
mod web_socket;
mod web_socket_route;
mod worker;
mod writable_stream;

pub use android::*;
pub use android_device::*;
pub use android_socket::*;
pub use android_types::*;
pub use api_request_context::*;
pub use api_types::*;
pub use artifact::*;
pub use binding_call::*;
pub use browser::*;
pub use browser_context::*;
pub use browser_type::*;
pub use cdp_session::*;
pub use core_types::*;
pub use debug_controller::*;
pub use debugger::*;
pub use dialog::*;
pub use disposable::*;
pub use electron::*;
pub use electron_application::*;
pub use element_handle::*;
pub use frame::*;
pub use frame_2::*;
pub use js_handle::*;
pub use json_pipe::*;
pub use local_utils::*;
pub use mixins_types::*;
pub use network_types::*;
pub use page::*;
pub use page_2::*;
pub use playwright::*;
pub use playwright_types::*;
pub use request::*;
pub use response::*;
pub use root::*;
pub use route::*;
pub use serialized_types::*;
pub use socks_support::*;
pub use stream::*;
pub use structs_types::*;
pub use tracing::*;
pub use web_socket::*;
pub use web_socket_route::*;
pub use worker::*;
pub use writable_stream::*;
