// @generated by scripts/generate-playwright-protocol.mjs from
// rust/protocol/playwright/*.yml. Do not edit by hand.

#![allow(clippy::all, missing_docs, unused_imports)]

use serde::{Deserialize, Serialize};

use super::*;
use crate::playwright::connection::{
    Binary, Channel, ChannelType, ObjectRef, ProtocolError, ProtocolEvent, Ref,
};

#[derive(Debug, Clone, Copy, Default, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum SetNetworkCookieSameSite {
    #[default]
    #[serde(rename = "Strict")]
    Strict,
    #[serde(rename = "Lax")]
    Lax,
    #[serde(rename = "None")]
    None,
}

/// `SetNetworkCookie` object from `network.yml`.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct SetNetworkCookie {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "value")]
    pub value: String,
    #[serde(rename = "url", default, skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
    #[serde(rename = "domain", default, skip_serializing_if = "Option::is_none")]
    pub domain: Option<String>,
    #[serde(rename = "path", default, skip_serializing_if = "Option::is_none")]
    pub path: Option<String>,
    #[serde(rename = "expires", default, skip_serializing_if = "Option::is_none")]
    pub expires: Option<f64>,
    #[serde(rename = "httpOnly", default, skip_serializing_if = "Option::is_none")]
    pub http_only: Option<bool>,
    #[serde(rename = "secure", default, skip_serializing_if = "Option::is_none")]
    pub secure: Option<bool>,
    #[serde(rename = "sameSite", default, skip_serializing_if = "Option::is_none")]
    pub same_site: Option<SetNetworkCookieSameSite>,
    #[serde(rename = "partitionKey", default, skip_serializing_if = "Option::is_none")]
    pub partition_key: Option<String>,
    #[serde(rename = "_crHasCrossSiteAncestor", default, skip_serializing_if = "Option::is_none")]
    pub cr_has_cross_site_ancestor: Option<bool>,
}

#[derive(Debug, Clone, Copy, Default, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum NetworkCookieSameSite {
    #[default]
    #[serde(rename = "Strict")]
    Strict,
    #[serde(rename = "Lax")]
    Lax,
    #[serde(rename = "None")]
    None,
}

/// `NetworkCookie` object from `network.yml`.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct NetworkCookie {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "value")]
    pub value: String,
    #[serde(rename = "domain")]
    pub domain: String,
    #[serde(rename = "path")]
    pub path: String,
    #[serde(rename = "expires")]
    pub expires: f64,
    #[serde(rename = "httpOnly")]
    pub http_only: bool,
    #[serde(rename = "secure")]
    pub secure: bool,
    #[serde(rename = "sameSite")]
    pub same_site: NetworkCookieSameSite,
    #[serde(rename = "partitionKey", default, skip_serializing_if = "Option::is_none")]
    pub partition_key: Option<String>,
    #[serde(rename = "_crHasCrossSiteAncestor", default, skip_serializing_if = "Option::is_none")]
    pub cr_has_cross_site_ancestor: Option<bool>,
}

/// `ResourceTiming` object from `network.yml`.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct ResourceTiming {
    #[serde(rename = "startTime")]
    pub start_time: f64,
    #[serde(rename = "domainLookupStart")]
    pub domain_lookup_start: f64,
    #[serde(rename = "domainLookupEnd")]
    pub domain_lookup_end: f64,
    #[serde(rename = "connectStart")]
    pub connect_start: f64,
    #[serde(rename = "secureConnectionStart")]
    pub secure_connection_start: f64,
    #[serde(rename = "connectEnd")]
    pub connect_end: f64,
    #[serde(rename = "requestStart")]
    pub request_start: f64,
    #[serde(rename = "responseStart")]
    pub response_start: f64,
}

/// `SecurityDetails` object from `network.yml`.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct SecurityDetails {
    #[serde(rename = "issuer", default, skip_serializing_if = "Option::is_none")]
    pub issuer: Option<String>,
    #[serde(rename = "protocol", default, skip_serializing_if = "Option::is_none")]
    pub protocol: Option<String>,
    #[serde(rename = "subjectName", default, skip_serializing_if = "Option::is_none")]
    pub subject_name: Option<String>,
    #[serde(rename = "validFrom", default, skip_serializing_if = "Option::is_none")]
    pub valid_from: Option<f64>,
    #[serde(rename = "validTo", default, skip_serializing_if = "Option::is_none")]
    pub valid_to: Option<f64>,
}

/// `RequestSizes` object from `network.yml`.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct RequestSizes {
    #[serde(rename = "requestBodySize")]
    pub request_body_size: i64,
    #[serde(rename = "requestHeadersSize")]
    pub request_headers_size: i64,
    #[serde(rename = "responseBodySize")]
    pub response_body_size: i64,
    #[serde(rename = "responseHeadersSize")]
    pub response_headers_size: i64,
}

/// `RemoteAddr` object from `network.yml`.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct RemoteAddr {
    #[serde(rename = "ipAddress")]
    pub ip_address: String,
    #[serde(rename = "port")]
    pub port: i64,
}
