// @generated by scripts/generate-playwright-protocol.mjs from
// rust/protocol/playwright/*.yml. Do not edit by hand.

#![allow(clippy::all, missing_docs, unused_imports)]

use serde::{Deserialize, Serialize};

use super::*;
use crate::playwright::connection::{
    Binary, Channel, ChannelType, ObjectRef, ProtocolError, ProtocolEvent, Ref,
};

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct PageInitializerViewportSize {
    #[serde(rename = "width")]
    pub width: i64,
    #[serde(rename = "height")]
    pub height: i64,
}

/// Initializer the driver sends when it creates a `Page`.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct PageInitializer {
    #[serde(rename = "mainFrame")]
    pub main_frame: Ref<Frame>,
    #[serde(rename = "viewportSize", default, skip_serializing_if = "Option::is_none")]
    pub viewport_size: Option<PageInitializerViewportSize>,
    #[serde(rename = "isClosed")]
    pub is_closed: bool,
    #[serde(rename = "opener", default, skip_serializing_if = "Option::is_none")]
    pub opener: Option<Ref<Page>>,
    #[serde(rename = "video", default, skip_serializing_if = "Option::is_none")]
    pub video: Option<Ref<Artifact>>,
}

/// Parameters of `Page.addInitScript` (Add init script).
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct PageAddInitScriptParams {
    #[serde(rename = "source")]
    pub source: String,
}

/// Result of `Page.addInitScript` (Add init script).
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct PageAddInitScriptResult {
    #[serde(rename = "disposable")]
    pub disposable: Ref<Disposable>,
}

/// Parameters of `Page.close` (Close page).
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct PageCloseParams {
    #[serde(rename = "reason", default, skip_serializing_if = "Option::is_none")]
    pub reason: Option<String>,
}

/// Parameters of `Page.consoleMessages` (Get console messages).
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct PageConsoleMessagesParams {
    #[serde(rename = "filter", default, skip_serializing_if = "Option::is_none")]
    pub filter: Option<ConsoleMessagesFilter>,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct PageConsoleMessagesResultMessages {
    /// Properties of the `ConsoleMessage` mixin.
    #[serde(flatten)]
    pub console_message: ConsoleMessage,
}

/// Result of `Page.consoleMessages` (Get console messages).
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct PageConsoleMessagesResult {
    #[serde(rename = "messages")]
    pub messages: Vec<PageConsoleMessagesResultMessages>,
}

#[derive(Debug, Clone, Copy, Default, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum PageEmulateMediaParamsMedia {
    #[default]
    #[serde(rename = "screen")]
    Screen,
    #[serde(rename = "print")]
    Print,
    #[serde(rename = "no-override")]
    NoOverride,
}

#[derive(Debug, Clone, Copy, Default, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum PageEmulateMediaParamsColorScheme {
    #[default]
    #[serde(rename = "dark")]
    Dark,
    #[serde(rename = "light")]
    Light,
    #[serde(rename = "no-preference")]
    NoPreference,
    #[serde(rename = "no-override")]
    NoOverride,
}

#[derive(Debug, Clone, Copy, Default, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum PageEmulateMediaParamsReducedMotion {
    #[default]
    #[serde(rename = "reduce")]
    Reduce,
    #[serde(rename = "no-preference")]
    NoPreference,
    #[serde(rename = "no-override")]
    NoOverride,
}

#[derive(Debug, Clone, Copy, Default, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum PageEmulateMediaParamsForcedColors {
    #[default]
    #[serde(rename = "active")]
    Active,
    #[serde(rename = "none")]
    None,
    #[serde(rename = "no-override")]
    NoOverride,
}

#[derive(Debug, Clone, Copy, Default, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum PageEmulateMediaParamsContrast {
    #[default]
    #[serde(rename = "no-preference")]
    NoPreference,
    #[serde(rename = "more")]
    More,
    #[serde(rename = "no-override")]
    NoOverride,
}

/// Parameters of `Page.emulateMedia` (Emulate media).
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct PageEmulateMediaParams {
    #[serde(rename = "media", default, skip_serializing_if = "Option::is_none")]
    pub media: Option<PageEmulateMediaParamsMedia>,
    #[serde(rename = "colorScheme", default, skip_serializing_if = "Option::is_none")]
    pub color_scheme: Option<PageEmulateMediaParamsColorScheme>,
    #[serde(rename = "reducedMotion", default, skip_serializing_if = "Option::is_none")]
    pub reduced_motion: Option<PageEmulateMediaParamsReducedMotion>,
    #[serde(rename = "forcedColors", default, skip_serializing_if = "Option::is_none")]
    pub forced_colors: Option<PageEmulateMediaParamsForcedColors>,
    #[serde(rename = "contrast", default, skip_serializing_if = "Option::is_none")]
    pub contrast: Option<PageEmulateMediaParamsContrast>,
}

/// Parameters of `Page.exposeBinding` (Expose binding).
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct PageExposeBindingParams {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "noGlobal", default, skip_serializing_if = "Option::is_none")]
    pub no_global: Option<bool>,
}

/// Result of `Page.exposeBinding` (Expose binding).
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct PageExposeBindingResult {
    #[serde(rename = "disposable")]
    pub disposable: Ref<Disposable>,
}

/// Parameters of `Page.goBack` (Go back).
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct PageGoBackParams {
    #[serde(rename = "waitUntil", default, skip_serializing_if = "Option::is_none")]
    pub wait_until: Option<LifecycleEvent>,
}

/// Result of `Page.goBack` (Go back).
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct PageGoBackResult {
    #[serde(rename = "response", default, skip_serializing_if = "Option::is_none")]
    pub response: Option<Ref<Response>>,
}

/// Parameters of `Page.goForward` (Go forward).
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct PageGoForwardParams {
    #[serde(rename = "waitUntil", default, skip_serializing_if = "Option::is_none")]
    pub wait_until: Option<LifecycleEvent>,
}

/// Result of `Page.goForward` (Go forward).
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct PageGoForwardResult {
    #[serde(rename = "response", default, skip_serializing_if = "Option::is_none")]
    pub response: Option<Ref<Response>>,
}

/// Parameters of `Page.registerLocatorHandler` (Register locator handler).
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct PageRegisterLocatorHandlerParams {
    #[serde(rename = "selector")]
    pub selector: String,
    #[serde(rename = "noWaitAfter", default, skip_serializing_if = "Option::is_none")]
    pub no_wait_after: Option<bool>,
}

/// Result of `Page.registerLocatorHandler` (Register locator handler).
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct PageRegisterLocatorHandlerResult {
    #[serde(rename = "uid")]
    pub uid: i64,
}

/// Parameters of `Page.resolveLocatorHandlerNoReply`.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct PageResolveLocatorHandlerNoReplyParams {
    #[serde(rename = "uid")]
    pub uid: i64,
    #[serde(rename = "remove", default, skip_serializing_if = "Option::is_none")]
    pub remove: Option<bool>,
}

/// Parameters of `Page.unregisterLocatorHandler` (Unregister locator handler).
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct PageUnregisterLocatorHandlerParams {
    #[serde(rename = "uid")]
    pub uid: i64,
}

/// Parameters of `Page.reload` (Reload).
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct PageReloadParams {
    #[serde(rename = "waitUntil", default, skip_serializing_if = "Option::is_none")]
    pub wait_until: Option<LifecycleEvent>,
}

/// Result of `Page.reload` (Reload).
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct PageReloadResult {
    #[serde(rename = "response", default, skip_serializing_if = "Option::is_none")]
    pub response: Option<Ref<Response>>,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct PageExpectScreenshotParamsLocator {
    #[serde(rename = "frame")]
    pub frame: Ref<Frame>,
    #[serde(rename = "selector")]
    pub selector: String,
}

#[derive(Debug, Clone, Copy, Default, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum PageExpectScreenshotParamsType {
    #[default]
    #[serde(rename = "png")]
    Png,
    #[serde(rename = "webp")]
    Webp,
}

/// Parameters of `Page.expectScreenshot` (Expect screenshot).
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct PageExpectScreenshotParams {
    #[serde(rename = "expected", default, skip_serializing_if = "Option::is_none")]
    pub expected: Option<Binary>,
    #[serde(rename = "isNot")]
    pub is_not: bool,
    #[serde(rename = "locator", default, skip_serializing_if = "Option::is_none")]
    pub locator: Option<PageExpectScreenshotParamsLocator>,
    #[serde(rename = "comparator", default, skip_serializing_if = "Option::is_none")]
    pub comparator: Option<String>,
    #[serde(rename = "maxDiffPixels", default, skip_serializing_if = "Option::is_none")]
    pub max_diff_pixels: Option<i64>,
    #[serde(rename = "maxDiffPixelRatio", default, skip_serializing_if = "Option::is_none")]
    pub max_diff_pixel_ratio: Option<f64>,
    #[serde(rename = "threshold", default, skip_serializing_if = "Option::is_none")]
    pub threshold: Option<f64>,
    #[serde(rename = "fullPage", default, skip_serializing_if = "Option::is_none")]
    pub full_page: Option<bool>,
    #[serde(rename = "clip", default, skip_serializing_if = "Option::is_none")]
    pub clip: Option<Rect>,
    #[serde(rename = "type", default, skip_serializing_if = "Option::is_none")]
    pub r#type: Option<PageExpectScreenshotParamsType>,
    /// Properties of the `CommonScreenshotOptions` mixin.
    #[serde(flatten)]
    pub common_screenshot_options: CommonScreenshotOptions,
}

/// Result of `Page.expectScreenshot` (Expect screenshot).
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct PageExpectScreenshotResult {
    #[serde(rename = "actual", default, skip_serializing_if = "Option::is_none")]
    pub actual: Option<Binary>,
}

#[derive(Debug, Clone, Copy, Default, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum PageScreenshotParamsType {
    #[default]
    #[serde(rename = "png")]
    Png,
    #[serde(rename = "jpeg")]
    Jpeg,
    #[serde(rename = "webp")]
    Webp,
}

/// Parameters of `Page.screenshot` (Screenshot).
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct PageScreenshotParams {
    #[serde(rename = "type", default, skip_serializing_if = "Option::is_none")]
    pub r#type: Option<PageScreenshotParamsType>,
    #[serde(rename = "quality", default, skip_serializing_if = "Option::is_none")]
    pub quality: Option<i64>,
    #[serde(rename = "fullPage", default, skip_serializing_if = "Option::is_none")]
    pub full_page: Option<bool>,
    #[serde(rename = "clip", default, skip_serializing_if = "Option::is_none")]
    pub clip: Option<Rect>,
    /// Properties of the `CommonScreenshotOptions` mixin.
    #[serde(flatten)]
    pub common_screenshot_options: CommonScreenshotOptions,
}

/// Result of `Page.screenshot` (Screenshot).
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct PageScreenshotResult {
    #[serde(rename = "binary")]
    pub binary: Binary,
}

/// Parameters of `Page.setExtraHTTPHeaders` (Set extra HTTP headers).
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct PageSetExtraHTTPHeadersParams {
    #[serde(rename = "headers")]
    pub headers: Vec<NameValue>,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct PageSetNetworkInterceptionPatternsParamsPatterns {
    #[serde(rename = "glob", default, skip_serializing_if = "Option::is_none")]
    pub glob: Option<String>,
    #[serde(rename = "regexSource", default, skip_serializing_if = "Option::is_none")]
    pub regex_source: Option<String>,
    #[serde(rename = "regexFlags", default, skip_serializing_if = "Option::is_none")]
    pub regex_flags: Option<String>,
    #[serde(rename = "urlPattern", default, skip_serializing_if = "Option::is_none")]
    pub url_pattern: Option<URLPattern>,
}

/// Parameters of `Page.setNetworkInterceptionPatterns` (Route requests).
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct PageSetNetworkInterceptionPatternsParams {
    #[serde(rename = "patterns")]
    pub patterns: Vec<PageSetNetworkInterceptionPatternsParamsPatterns>,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct PageSetWebSocketInterceptionPatternsParamsPatterns {
    #[serde(rename = "glob", default, skip_serializing_if = "Option::is_none")]
    pub glob: Option<String>,
    #[serde(rename = "regexSource", default, skip_serializing_if = "Option::is_none")]
    pub regex_source: Option<String>,
    #[serde(rename = "regexFlags", default, skip_serializing_if = "Option::is_none")]
    pub regex_flags: Option<String>,
    #[serde(rename = "urlPattern", default, skip_serializing_if = "Option::is_none")]
    pub url_pattern: Option<URLPattern>,
}

/// Parameters of `Page.setWebSocketInterceptionPatterns` (Route WebSockets).
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct PageSetWebSocketInterceptionPatternsParams {
    #[serde(rename = "patterns")]
    pub patterns: Vec<PageSetWebSocketInterceptionPatternsParamsPatterns>,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct PageSetViewportSizeParamsViewportSize {
    #[serde(rename = "width")]
    pub width: i64,
    #[serde(rename = "height")]
    pub height: i64,
}

/// Parameters of `Page.setViewportSize` (Set viewport size).
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct PageSetViewportSizeParams {
    #[serde(rename = "viewportSize")]
    pub viewport_size: PageSetViewportSizeParamsViewportSize,
}

/// Parameters of `Page.keyboardDown` (Key down "{key}").
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct PageKeyboardDownParams {
    #[serde(rename = "key")]
    pub key: String,
}

/// Parameters of `Page.keyboardUp` (Key up "{key}").
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct PageKeyboardUpParams {
    #[serde(rename = "key")]
    pub key: String,
}

/// Parameters of `Page.keyboardInsertText` (Insert "{text}").
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct PageKeyboardInsertTextParams {
    #[serde(rename = "text")]
    pub text: String,
}

/// Parameters of `Page.keyboardType` (Type "{text}").
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct PageKeyboardTypeParams {
    #[serde(rename = "text")]
    pub text: String,
    #[serde(rename = "delay", default, skip_serializing_if = "Option::is_none")]
    pub delay: Option<f64>,
}

/// Parameters of `Page.keyboardPress` (Press "{key}").
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct PageKeyboardPressParams {
    #[serde(rename = "key")]
    pub key: String,
    #[serde(rename = "delay", default, skip_serializing_if = "Option::is_none")]
    pub delay: Option<f64>,
}

/// Parameters of `Page.mouseMove` (Mouse move).
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct PageMouseMoveParams {
    #[serde(rename = "x")]
    pub x: f64,
    #[serde(rename = "y")]
    pub y: f64,
    #[serde(rename = "steps", default, skip_serializing_if = "Option::is_none")]
    pub steps: Option<i64>,
}

#[derive(Debug, Clone, Copy, Default, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum PageMouseDownParamsButton {
    #[default]
    #[serde(rename = "left")]
    Left,
    #[serde(rename = "right")]
    Right,
    #[serde(rename = "middle")]
    Middle,
}

/// Parameters of `Page.mouseDown` (Mouse down).
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct PageMouseDownParams {
    #[serde(rename = "button", default, skip_serializing_if = "Option::is_none")]
    pub button: Option<PageMouseDownParamsButton>,
    #[serde(rename = "clickCount", default, skip_serializing_if = "Option::is_none")]
    pub click_count: Option<i64>,
}

#[derive(Debug, Clone, Copy, Default, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum PageMouseUpParamsButton {
    #[default]
    #[serde(rename = "left")]
    Left,
    #[serde(rename = "right")]
    Right,
    #[serde(rename = "middle")]
    Middle,
}

/// Parameters of `Page.mouseUp` (Mouse up).
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct PageMouseUpParams {
    #[serde(rename = "button", default, skip_serializing_if = "Option::is_none")]
    pub button: Option<PageMouseUpParamsButton>,
    #[serde(rename = "clickCount", default, skip_serializing_if = "Option::is_none")]
    pub click_count: Option<i64>,
}

#[derive(Debug, Clone, Copy, Default, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum PageMouseClickParamsButton {
    #[default]
    #[serde(rename = "left")]
    Left,
    #[serde(rename = "right")]
    Right,
    #[serde(rename = "middle")]
    Middle,
}

/// Parameters of `Page.mouseClick` (Click).
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct PageMouseClickParams {
    #[serde(rename = "x")]
    pub x: f64,
    #[serde(rename = "y")]
    pub y: f64,
    #[serde(rename = "delay", default, skip_serializing_if = "Option::is_none")]
    pub delay: Option<f64>,
    #[serde(rename = "button", default, skip_serializing_if = "Option::is_none")]
    pub button: Option<PageMouseClickParamsButton>,
    #[serde(rename = "clickCount", default, skip_serializing_if = "Option::is_none")]
    pub click_count: Option<i64>,
}

/// Parameters of `Page.mouseWheel` (Mouse wheel).
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct PageMouseWheelParams {
    #[serde(rename = "deltaX")]
    pub delta_x: f64,
    #[serde(rename = "deltaY")]
    pub delta_y: f64,
}

/// Parameters of `Page.touchscreenTap` (Tap).
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct PageTouchscreenTapParams {
    #[serde(rename = "x")]
    pub x: f64,
    #[serde(rename = "y")]
    pub y: f64,
}

/// Parameters of `Page.pageErrors` (Get page errors).
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct PagePageErrorsParams {
    #[serde(rename = "filter", default, skip_serializing_if = "Option::is_none")]
    pub filter: Option<ConsoleMessagesFilter>,
}

/// Result of `Page.pageErrors` (Get page errors).
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct PagePageErrorsResult {
    #[serde(rename = "errors")]
    pub errors: Vec<SerializedError>,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct PagePdfParamsMargin {
    #[serde(rename = "top", default, skip_serializing_if = "Option::is_none")]
    pub top: Option<String>,
    #[serde(rename = "bottom", default, skip_serializing_if = "Option::is_none")]
    pub bottom: Option<String>,
    #[serde(rename = "left", default, skip_serializing_if = "Option::is_none")]
    pub left: Option<String>,
    #[serde(rename = "right", default, skip_serializing_if = "Option::is_none")]
    pub right: Option<String>,
}

/// Parameters of `Page.pdf` (PDF).
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct PagePdfParams {
    #[serde(rename = "scale", default, skip_serializing_if = "Option::is_none")]
    pub scale: Option<f64>,
    #[serde(rename = "displayHeaderFooter", default, skip_serializing_if = "Option::is_none")]
    pub display_header_footer: Option<bool>,
    #[serde(rename = "headerTemplate", default, skip_serializing_if = "Option::is_none")]
    pub header_template: Option<String>,
    #[serde(rename = "footerTemplate", default, skip_serializing_if = "Option::is_none")]
    pub footer_template: Option<String>,
    #[serde(rename = "printBackground", default, skip_serializing_if = "Option::is_none")]
    pub print_background: Option<bool>,
    #[serde(rename = "landscape", default, skip_serializing_if = "Option::is_none")]
    pub landscape: Option<bool>,
    #[serde(rename = "pageRanges", default, skip_serializing_if = "Option::is_none")]
    pub page_ranges: Option<String>,
    #[serde(rename = "format", default, skip_serializing_if = "Option::is_none")]
    pub format: Option<String>,
    #[serde(rename = "width", default, skip_serializing_if = "Option::is_none")]
    pub width: Option<String>,
    #[serde(rename = "height", default, skip_serializing_if = "Option::is_none")]
    pub height: Option<String>,
    #[serde(rename = "preferCSSPageSize", default, skip_serializing_if = "Option::is_none")]
    pub prefer_css_page_size: Option<bool>,
    #[serde(rename = "margin", default, skip_serializing_if = "Option::is_none")]
    pub margin: Option<PagePdfParamsMargin>,
    #[serde(rename = "tagged", default, skip_serializing_if = "Option::is_none")]
    pub tagged: Option<bool>,
    #[serde(rename = "outline", default, skip_serializing_if = "Option::is_none")]
    pub outline: Option<bool>,
}

/// Result of `Page.pdf` (PDF).
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct PagePdfResult {
    #[serde(rename = "pdf")]
    pub pdf: Binary,
}

/// Result of `Page.requests` (Get network requests).
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct PageRequestsResult {
    #[serde(rename = "requests")]
    pub requests: Vec<Ref<Request>>,
}

/// Parameters of `Page.startJSCoverage` (Start JS coverage).
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct PageStartJSCoverageParams {
    #[serde(rename = "resetOnNavigation", default, skip_serializing_if = "Option::is_none")]
    pub reset_on_navigation: Option<bool>,
    #[serde(rename = "reportAnonymousScripts", default, skip_serializing_if = "Option::is_none")]
    pub report_anonymous_scripts: Option<bool>,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct PageStopJSCoverageResultEntriesFunctionsRanges {
    #[serde(rename = "startOffset")]
    pub start_offset: i64,
    #[serde(rename = "endOffset")]
    pub end_offset: i64,
    #[serde(rename = "count")]
    pub count: i64,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct PageStopJSCoverageResultEntriesFunctions {
    #[serde(rename = "functionName")]
    pub function_name: String,
    #[serde(rename = "isBlockCoverage")]
    pub is_block_coverage: bool,
    #[serde(rename = "ranges")]
    pub ranges: Vec<PageStopJSCoverageResultEntriesFunctionsRanges>,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct PageStopJSCoverageResultEntries {
    #[serde(rename = "url")]
    pub url: String,
    #[serde(rename = "scriptId")]
    pub script_id: String,
    #[serde(rename = "source", default, skip_serializing_if = "Option::is_none")]
    pub source: Option<String>,
    #[serde(rename = "functions")]
    pub functions: Vec<PageStopJSCoverageResultEntriesFunctions>,
}

/// Result of `Page.stopJSCoverage` (Stop JS coverage).
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct PageStopJSCoverageResult {
    #[serde(rename = "entries")]
    pub entries: Vec<PageStopJSCoverageResultEntries>,
}

/// Parameters of `Page.startCSSCoverage` (Start CSS coverage).
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct PageStartCSSCoverageParams {
    #[serde(rename = "resetOnNavigation", default, skip_serializing_if = "Option::is_none")]
    pub reset_on_navigation: Option<bool>,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct PageStopCSSCoverageResultEntriesRanges {
    #[serde(rename = "start")]
    pub start: i64,
    #[serde(rename = "end")]
    pub end: i64,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct PageStopCSSCoverageResultEntries {
    #[serde(rename = "url")]
    pub url: String,
    #[serde(rename = "text", default, skip_serializing_if = "Option::is_none")]
    pub text: Option<String>,
    #[serde(rename = "ranges")]
    pub ranges: Vec<PageStopCSSCoverageResultEntriesRanges>,
}

/// Result of `Page.stopCSSCoverage` (Stop CSS coverage).
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct PageStopCSSCoverageResult {
    #[serde(rename = "entries")]
    pub entries: Vec<PageStopCSSCoverageResultEntries>,
}

/// Result of `Page.pickLocator` (Pick locator).
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct PagePickLocatorResult {
    #[serde(rename = "selector")]
    pub selector: String,
}

/// Parameters of `Page.screencastShowOverlay` (Show overlay).
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct PageScreencastShowOverlayParams {
    #[serde(rename = "html")]
    pub html: String,
    #[serde(rename = "duration", default, skip_serializing_if = "Option::is_none")]
    pub duration: Option<f64>,
}

/// Result of `Page.screencastShowOverlay` (Show overlay).
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct PageScreencastShowOverlayResult {
    #[serde(rename = "id")]
    pub id: String,
}

/// Parameters of `Page.screencastRemoveOverlay` (Remove overlay).
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct PageScreencastRemoveOverlayParams {
    #[serde(rename = "id")]
    pub id: String,
}

/// Parameters of `Page.screencastChapter` (Show chapter overlay).
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct PageScreencastChapterParams {
    #[serde(rename = "title")]
    pub title: String,
    #[serde(rename = "description", default, skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "duration", default, skip_serializing_if = "Option::is_none")]
    pub duration: Option<f64>,
}

/// Parameters of `Page.screencastSetOverlayVisible` (Set overlay visibility).
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct PageScreencastSetOverlayVisibleParams {
    #[serde(rename = "visible")]
    pub visible: bool,
}

/// Parameters of `Page.screencastShowActions` (Show actions).
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct PageScreencastShowActionsParams {
    /// Properties of the `ShowActionsOptions` mixin.
    #[serde(flatten)]
    pub show_actions_options: ShowActionsOptions,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct PageScreencastStartParamsSize {
    #[serde(rename = "width")]
    pub width: i64,
    #[serde(rename = "height")]
    pub height: i64,
}

/// Parameters of `Page.screencastStart` (Start screencast).
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct PageScreencastStartParams {
    #[serde(rename = "size", default, skip_serializing_if = "Option::is_none")]
    pub size: Option<PageScreencastStartParamsSize>,
    #[serde(rename = "quality", default, skip_serializing_if = "Option::is_none")]
    pub quality: Option<i64>,
    #[serde(rename = "sendFrames", default, skip_serializing_if = "Option::is_none")]
    pub send_frames: Option<bool>,
    #[serde(rename = "record", default, skip_serializing_if = "Option::is_none")]
    pub record: Option<bool>,
}

/// Result of `Page.screencastStart` (Start screencast).
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct PageScreencastStartResult {
    #[serde(rename = "artifact", default, skip_serializing_if = "Option::is_none")]
    pub artifact: Option<Ref<Artifact>>,
}

/// Parameters of `Page.screencastFrameAck`.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct PageScreencastFrameAckParams {
    #[serde(rename = "frameId")]
    pub frame_id: i64,
}

#[derive(Debug, Clone, Copy, Default, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum PageUpdateSubscriptionParamsEvent {
    #[default]
    #[serde(rename = "console")]
    Console,
    #[serde(rename = "dialog")]
    Dialog,
    #[serde(rename = "dialogClosed")]
    DialogClosed,
    #[serde(rename = "fileChooser")]
    FileChooser,
    #[serde(rename = "request")]
    Request,
    #[serde(rename = "response")]
    Response,
    #[serde(rename = "requestFinished")]
    RequestFinished,
    #[serde(rename = "requestFailed")]
    RequestFailed,
}

/// Parameters of `Page.updateSubscription`.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct PageUpdateSubscriptionParams {
    #[serde(rename = "event")]
    pub event: PageUpdateSubscriptionParamsEvent,
    #[serde(rename = "enabled")]
    pub enabled: bool,
}

/// Parameters of `Page.setDockTile`.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct PageSetDockTileParams {
    #[serde(rename = "image")]
    pub image: Binary,
}

#[derive(Debug, Clone, Copy, Default, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum PageWebStorageItemsParamsKind {
    #[default]
    #[serde(rename = "local")]
    Local,
    #[serde(rename = "session")]
    Session,
}

/// Parameters of `Page.webStorageItems` (Get WebStorage items).
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct PageWebStorageItemsParams {
    #[serde(rename = "kind")]
    pub kind: PageWebStorageItemsParamsKind,
}

/// Result of `Page.webStorageItems` (Get WebStorage items).
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct PageWebStorageItemsResult {
    #[serde(rename = "items")]
    pub items: Vec<NameValue>,
}

#[derive(Debug, Clone, Copy, Default, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum PageWebStorageGetItemParamsKind {
    #[default]
    #[serde(rename = "local")]
    Local,
    #[serde(rename = "session")]
    Session,
}

/// Parameters of `Page.webStorageGetItem` (Get WebStorage item).
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct PageWebStorageGetItemParams {
    #[serde(rename = "kind")]
    pub kind: PageWebStorageGetItemParamsKind,
    #[serde(rename = "name")]
    pub name: String,
}

/// Result of `Page.webStorageGetItem` (Get WebStorage item).
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct PageWebStorageGetItemResult {
    #[serde(rename = "value", default, skip_serializing_if = "Option::is_none")]
    pub value: Option<String>,
}

#[derive(Debug, Clone, Copy, Default, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum PageWebStorageSetItemParamsKind {
    #[default]
    #[serde(rename = "local")]
    Local,
    #[serde(rename = "session")]
    Session,
}

/// Parameters of `Page.webStorageSetItem` (Set WebStorage item).
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct PageWebStorageSetItemParams {
    #[serde(rename = "kind")]
    pub kind: PageWebStorageSetItemParamsKind,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "value")]
    pub value: String,
}

#[derive(Debug, Clone, Copy, Default, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum PageWebStorageRemoveItemParamsKind {
    #[default]
    #[serde(rename = "local")]
    Local,
    #[serde(rename = "session")]
    Session,
}

/// Parameters of `Page.webStorageRemoveItem` (Remove WebStorage item).
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct PageWebStorageRemoveItemParams {
    #[serde(rename = "kind")]
    pub kind: PageWebStorageRemoveItemParamsKind,
    #[serde(rename = "name")]
    pub name: String,
}

#[derive(Debug, Clone, Copy, Default, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum PageWebStorageClearParamsKind {
    #[default]
    #[serde(rename = "local")]
    Local,
    #[serde(rename = "session")]
    Session,
}

/// Parameters of `Page.webStorageClear` (Clear WebStorage).
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct PageWebStorageClearParams {
    #[serde(rename = "kind")]
    pub kind: PageWebStorageClearParamsKind,
}

/// Payload of the `Page.bindingCall` event.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct PageBindingCallEventParams {
    #[serde(rename = "binding")]
    pub binding: Ref<BindingCall>,
}

/// Payload of the `Page.download` event.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct PageDownloadEventParams {
    #[serde(rename = "url")]
    pub url: String,
    #[serde(rename = "suggestedFilename")]
    pub suggested_filename: String,
    #[serde(rename = "artifact")]
    pub artifact: Ref<Artifact>,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct PageViewportSizeChangedEventParamsViewportSize {
    #[serde(rename = "width")]
    pub width: i64,
    #[serde(rename = "height")]
    pub height: i64,
}

/// Payload of the `Page.viewportSizeChanged` event.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct PageViewportSizeChangedEventParams {
    #[serde(rename = "viewportSize", default, skip_serializing_if = "Option::is_none")]
    pub viewport_size: Option<PageViewportSizeChangedEventParamsViewportSize>,
}

/// Payload of the `Page.fileChooser` event.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct PageFileChooserEventParams {
    #[serde(rename = "element")]
    pub element: Ref<ElementHandle>,
    #[serde(rename = "isMultiple")]
    pub is_multiple: bool,
}

