// @generated by scripts/generate-playwright-protocol.mjs from
// rust/protocol/playwright/*.yml. Do not edit by hand.

#![allow(clippy::all, missing_docs, unused_imports)]

use serde::{Deserialize, Serialize};

use super::*;
use crate::playwright::connection::{
    Binary, Channel, ChannelType, ObjectRef, ProtocolError, ProtocolEvent, Ref,
};

/// `ExpectedTextValue` object from `playwright.yml`.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct ExpectedTextValue {
    #[serde(rename = "string", default, skip_serializing_if = "Option::is_none")]
    pub string: Option<String>,
    #[serde(rename = "regexSource", default, skip_serializing_if = "Option::is_none")]
    pub regex_source: Option<String>,
    #[serde(rename = "regexFlags", default, skip_serializing_if = "Option::is_none")]
    pub regex_flags: Option<String>,
    #[serde(rename = "matchSubstring", default, skip_serializing_if = "Option::is_none")]
    pub match_substring: Option<bool>,
    #[serde(rename = "ignoreCase", default, skip_serializing_if = "Option::is_none")]
    pub ignore_case: Option<bool>,
    #[serde(rename = "normalizeWhiteSpace", default, skip_serializing_if = "Option::is_none")]
    pub normalize_white_space: Option<bool>,
}

/// `SelectorEngine` object from `playwright.yml`.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct SelectorEngine {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "source")]
    pub source: String,
    #[serde(rename = "contentScript", default, skip_serializing_if = "Option::is_none")]
    pub content_script: Option<bool>,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct FormFieldFile {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "mimeType", default, skip_serializing_if = "Option::is_none")]
    pub mime_type: Option<String>,
    #[serde(rename = "buffer")]
    pub buffer: Binary,
}

/// `FormField` object from `playwright.yml`.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct FormField {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "value", default, skip_serializing_if = "Option::is_none")]
    pub value: Option<String>,
    #[serde(rename = "file", default, skip_serializing_if = "Option::is_none")]
    pub file: Option<FormFieldFile>,
}

/// `LifecycleEvent` enum from `playwright.yml`.
#[derive(Debug, Clone, Copy, Default, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum LifecycleEvent {
    #[default]
    #[serde(rename = "load")]
    Load,
    #[serde(rename = "domcontentloaded")]
    Domcontentloaded,
    #[serde(rename = "networkidle")]
    Networkidle,
    #[serde(rename = "commit")]
    Commit,
}

/// `ConsoleMessagesFilter` enum from `playwright.yml`.
#[derive(Debug, Clone, Copy, Default, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum ConsoleMessagesFilter {
    #[default]
    #[serde(rename = "all")]
    All,
    #[serde(rename = "since-navigation")]
    SinceNavigation,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct RecorderSourceHighlight {
    #[serde(rename = "line")]
    pub line: i64,
    #[serde(rename = "type")]
    pub r#type: String,
}

/// `RecorderSource` object from `playwright.yml`.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct RecorderSource {
    #[serde(rename = "isRecorded")]
    pub is_recorded: bool,
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "label")]
    pub label: String,
    #[serde(rename = "text")]
    pub text: String,
    #[serde(rename = "language")]
    pub language: String,
    #[serde(rename = "highlight")]
    pub highlight: Vec<RecorderSourceHighlight>,
    #[serde(rename = "revealLine", default, skip_serializing_if = "Option::is_none")]
    pub reveal_line: Option<i64>,
    #[serde(rename = "group", default, skip_serializing_if = "Option::is_none")]
    pub group: Option<String>,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct IndexedDBDatabaseStoresRecords {
    #[serde(rename = "key", default, skip_serializing_if = "Option::is_none")]
    pub key: Option<serde_json::Value>,
    #[serde(rename = "keyEncoded", default, skip_serializing_if = "Option::is_none")]
    pub key_encoded: Option<serde_json::Value>,
    #[serde(rename = "value", default, skip_serializing_if = "Option::is_none")]
    pub value: Option<serde_json::Value>,
    #[serde(rename = "valueEncoded", default, skip_serializing_if = "Option::is_none")]
    pub value_encoded: Option<serde_json::Value>,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct IndexedDBDatabaseStoresIndexes {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "keyPath", default, skip_serializing_if = "Option::is_none")]
    pub key_path: Option<String>,
    #[serde(rename = "keyPathArray", default, skip_serializing_if = "Option::is_none")]
    pub key_path_array: Option<Vec<String>>,
    #[serde(rename = "multiEntry")]
    pub multi_entry: bool,
    #[serde(rename = "unique")]
    pub unique: bool,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct IndexedDBDatabaseStores {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "autoIncrement")]
    pub auto_increment: bool,
    #[serde(rename = "keyPath", default, skip_serializing_if = "Option::is_none")]
    pub key_path: Option<String>,
    #[serde(rename = "keyPathArray", default, skip_serializing_if = "Option::is_none")]
    pub key_path_array: Option<Vec<String>>,
    #[serde(rename = "records")]
    pub records: Vec<IndexedDBDatabaseStoresRecords>,
    #[serde(rename = "indexes")]
    pub indexes: Vec<IndexedDBDatabaseStoresIndexes>,
}

/// `IndexedDBDatabase` object from `playwright.yml`.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct IndexedDBDatabase {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "version")]
    pub version: i64,
    #[serde(rename = "stores")]
    pub stores: Vec<IndexedDBDatabaseStores>,
}

/// `SetOriginStorage` object from `playwright.yml`.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct SetOriginStorage {
    #[serde(rename = "origin")]
    pub origin: String,
    #[serde(rename = "localStorage")]
    pub local_storage: Vec<NameValue>,
    #[serde(rename = "indexedDB", default, skip_serializing_if = "Option::is_none")]
    pub indexed_db: Option<Vec<IndexedDBDatabase>>,
}

/// `OriginStorage` object from `playwright.yml`.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct OriginStorage {
    #[serde(rename = "origin")]
    pub origin: String,
    #[serde(rename = "localStorage")]
    pub local_storage: Vec<NameValue>,
    #[serde(rename = "indexedDB", default, skip_serializing_if = "Option::is_none")]
    pub indexed_db: Option<Vec<IndexedDBDatabase>>,
}

#[derive(Debug, Clone, Copy, Default, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum RecordHarOptionsContent {
    #[default]
    #[serde(rename = "embed")]
    Embed,
    #[serde(rename = "attach")]
    Attach,
    #[serde(rename = "omit")]
    Omit,
}

#[derive(Debug, Clone, Copy, Default, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum RecordHarOptionsMode {
    #[default]
    #[serde(rename = "full")]
    Full,
    #[serde(rename = "minimal")]
    Minimal,
}

/// `RecordHarOptions` object from `playwright.yml`.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct RecordHarOptions {
    #[serde(rename = "content", default, skip_serializing_if = "Option::is_none")]
    pub content: Option<RecordHarOptionsContent>,
    #[serde(rename = "mode", default, skip_serializing_if = "Option::is_none")]
    pub mode: Option<RecordHarOptionsMode>,
    #[serde(rename = "urlGlob", default, skip_serializing_if = "Option::is_none")]
    pub url_glob: Option<String>,
    #[serde(rename = "urlRegexSource", default, skip_serializing_if = "Option::is_none")]
    pub url_regex_source: Option<String>,
    #[serde(rename = "urlRegexFlags", default, skip_serializing_if = "Option::is_none")]
    pub url_regex_flags: Option<String>,
    #[serde(rename = "harPath", default, skip_serializing_if = "Option::is_none")]
    pub har_path: Option<String>,
    #[serde(rename = "resourcesDir", default, skip_serializing_if = "Option::is_none")]
    pub resources_dir: Option<String>,
}
