// @generated by scripts/generate-playwright-protocol.mjs from
// rust/protocol/playwright/*.yml. Do not edit by hand.

#![allow(clippy::all, missing_docs, unused_imports)]

use serde::{Deserialize, Serialize};

use super::*;
use crate::playwright::connection::{
    Binary, Channel, ChannelType, ObjectRef, ProtocolError, ProtocolEvent, Ref,
};

/// Initializer the driver sends when it creates a `WebSocket`.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct WebSocketInitializer {
    #[serde(rename = "url")]
    pub url: String,
}

/// Payload of the `WebSocket.frameSent` event.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct WebSocketFrameSentEventParams {
    #[serde(rename = "opcode")]
    pub opcode: i64,
    #[serde(rename = "data")]
    pub data: String,
}

/// Payload of the `WebSocket.frameReceived` event.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct WebSocketFrameReceivedEventParams {
    #[serde(rename = "opcode")]
    pub opcode: i64,
    #[serde(rename = "data")]
    pub data: String,
}

/// Payload of the `WebSocket.socketError` event.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct WebSocketSocketErrorEventParams {
    #[serde(rename = "error")]
    pub error: String,
}

/// Events a `WebSocket` channel can emit.
#[derive(Debug, Clone, PartialEq)]
pub enum WebSocketEvent {
    /// `WebSocket.open`
    Open,
    /// `WebSocket.frameSent`
    FrameSent(WebSocketFrameSentEventParams),
    /// `WebSocket.frameReceived`
    FrameReceived(WebSocketFrameReceivedEventParams),
    /// `WebSocket.socketError`
    SocketError(WebSocketSocketErrorEventParams),
    /// `WebSocket.close`
    Close,
    /// An event this binding does not know (a newer driver).
    Unknown {
        /// Event name.
        method: String,
        /// Raw event parameters.
        params: serde_json::Value,
    },
}

impl ProtocolEvent for WebSocketEvent {
    fn parse(method: &str, params: serde_json::Value) -> Result<Self, serde_json::Error> {
        match method {
            "open" => Ok(Self::Open),
            "frameSent" => Ok(Self::FrameSent(serde_json::from_value(params)?)),
            "frameReceived" => Ok(Self::FrameReceived(serde_json::from_value(params)?)),
            "socketError" => Ok(Self::SocketError(serde_json::from_value(params)?)),
            "close" => Ok(Self::Close),
            _ => Ok(Self::Unknown { method: method.to_string(), params }),
        }
    }
}

/// Channel for the `WebSocket` interface (`network.yml`).
#[derive(Debug, Clone)]
pub struct WebSocket {
    channel: Channel,
}

impl ChannelType for WebSocket {
    const INTERFACE: &'static str = "WebSocket";
    type Initializer = WebSocketInitializer;
    type Event = WebSocketEvent;

    fn accepts(interface: &str) -> bool {
        matches!(interface, "WebSocket")
    }

    fn from_channel(channel: Channel) -> Self {
        Self { channel }
    }

    fn channel(&self) -> &Channel {
        &self.channel
    }
}

impl WebSocket {
}
