// @generated by scripts/generate-playwright-protocol.mjs from
// rust/protocol/playwright/*.yml. Do not edit by hand.

#![allow(clippy::all, missing_docs, unused_imports)]

use serde::{Deserialize, Serialize};

use super::*;
use crate::playwright::connection::{
    Binary, Channel, ChannelType, ObjectRef, ProtocolError, ProtocolEvent, Ref,
};

/// Initializer the driver sends when it creates a `Worker`.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct WorkerInitializer {
    #[serde(rename = "url")]
    pub url: String,
}

/// Parameters of `Worker.disconnect` (Disconnect from worker).
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct WorkerDisconnectParams {
    #[serde(rename = "reason", default, skip_serializing_if = "Option::is_none")]
    pub reason: Option<String>,
}

/// Parameters of `Worker.evaluateExpression` (Evaluate).
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct WorkerEvaluateExpressionParams {
    #[serde(rename = "expression")]
    pub expression: String,
    #[serde(rename = "isFunction", default, skip_serializing_if = "Option::is_none")]
    pub is_function: Option<bool>,
    #[serde(rename = "arg")]
    pub arg: SerializedArgument,
}

/// Result of `Worker.evaluateExpression` (Evaluate).
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct WorkerEvaluateExpressionResult {
    #[serde(rename = "value")]
    pub value: SerializedValue,
}

/// Parameters of `Worker.evaluateExpressionHandle` (Evaluate).
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct WorkerEvaluateExpressionHandleParams {
    #[serde(rename = "expression")]
    pub expression: String,
    #[serde(rename = "isFunction", default, skip_serializing_if = "Option::is_none")]
    pub is_function: Option<bool>,
    #[serde(rename = "arg")]
    pub arg: SerializedArgument,
}

/// Result of `Worker.evaluateExpressionHandle` (Evaluate).
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct WorkerEvaluateExpressionHandleResult {
    #[serde(rename = "handle")]
    pub handle: Ref<JSHandle>,
}

#[derive(Debug, Clone, Copy, Default, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum WorkerUpdateSubscriptionParamsEvent {
    #[default]
    #[serde(rename = "console")]
    Console,
}

/// Parameters of `Worker.updateSubscription`.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct WorkerUpdateSubscriptionParams {
    #[serde(rename = "event")]
    pub event: WorkerUpdateSubscriptionParamsEvent,
    #[serde(rename = "enabled")]
    pub enabled: bool,
}

/// Payload of the `Worker.console` event.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct WorkerConsoleEventParams {
    /// Properties of the `ConsoleMessage` mixin.
    #[serde(flatten)]
    pub console_message: ConsoleMessage,
}

/// Events a `Worker` channel can emit.
#[derive(Debug, Clone, PartialEq)]
pub enum WorkerEvent {
    /// `Worker.console`
    Console(WorkerConsoleEventParams),
    /// `Worker.close`
    Close,
    /// An event this binding does not know (a newer driver).
    Unknown {
        /// Event name.
        method: String,
        /// Raw event parameters.
        params: serde_json::Value,
    },
}

impl ProtocolEvent for WorkerEvent {
    fn parse(method: &str, params: serde_json::Value) -> Result<Self, serde_json::Error> {
        match method {
            "console" => Ok(Self::Console(serde_json::from_value(params)?)),
            "close" => Ok(Self::Close),
            _ => Ok(Self::Unknown { method: method.to_string(), params }),
        }
    }
}

/// Channel for the `Worker` interface (`worker.yml`).
#[derive(Debug, Clone)]
pub struct Worker {
    channel: Channel,
}

impl ChannelType for Worker {
    const INTERFACE: &'static str = "Worker";
    type Initializer = WorkerInitializer;
    type Event = WorkerEvent;

    fn accepts(interface: &str) -> bool {
        matches!(interface, "Worker")
    }

    fn from_channel(channel: Channel) -> Self {
        Self { channel }
    }

    fn channel(&self) -> &Channel {
        &self.channel
    }
}

impl Worker {
    /// `Worker.disconnect` ("Disconnect from worker").
    pub async fn disconnect(&self, params: WorkerDisconnectParams) -> Result<(), ProtocolError> {
        self.channel.send_no_result("disconnect", &params).await
    }

    /// `Worker.evaluateExpression` ("Evaluate").
    pub async fn evaluate_expression(&self, params: WorkerEvaluateExpressionParams) -> Result<WorkerEvaluateExpressionResult, ProtocolError> {
        self.channel.send("evaluateExpression", &params).await
    }

    /// `Worker.evaluateExpressionHandle` ("Evaluate").
    pub async fn evaluate_expression_handle(&self, params: WorkerEvaluateExpressionHandleParams) -> Result<WorkerEvaluateExpressionHandleResult, ProtocolError> {
        self.channel.send("evaluateExpressionHandle", &params).await
    }

    /// `Worker.updateSubscription` (internal).
    pub async fn update_subscription(&self, params: WorkerUpdateSubscriptionParams) -> Result<(), ProtocolError> {
        self.channel.send_no_result("updateSubscription", &params).await
    }
}
