# @generated by scripts/generate-puppeteer-bindings.mjs from
# rust/protocol/puppeteer/api.json. Do not edit by hand.
"""Typed wrappers of Puppeteer's API (puppeteer-core 25.12.0).

47 types; importing this package registers them with the bridge.
"""

from .accessibility import Accessibility
from .bluetooth_emulation import BluetoothEmulation
from .browser import Browser
from .browser_context import BrowserContext
from .browser_launcher import BrowserLauncher
from .cdp_session import CDPSession
from .common_event_emitter import CommonEventEmitter
from .connection import Connection
from .connection_closed_error import ConnectionClosedError
from .connection_transport import ConnectionTransport
from .console_message import ConsoleMessage
from .coverage import Coverage
from .css_coverage import CSSCoverage
from .device_request_prompt import DeviceRequestPrompt
from .dialog import Dialog
from .element_handle import ElementHandle
from .event_emitter import EventEmitter
from .extension import Extension
from .extension_transport import ExtensionTransport
from .file_chooser import FileChooser
from .frame import Frame
from .http_request import HTTPRequest
from .http_response import HTTPResponse
from .js_coverage import JSCoverage
from .js_handle import JSHandle
from .keyboard import Keyboard
from .locator import Locator
from .mouse import Mouse
from .moveable import Moveable
from .page import Page
from .protocol_error import ProtocolError
from .puppeteer import Puppeteer
from .puppeteer_error import PuppeteerError
from .puppeteer_node import PuppeteerNode
from .realm import Realm
from .screen_recorder import ScreenRecorder
from .screen_recording import ScreenRecording
from .security_details import SecurityDetails
from .serialized_ax_node import SerializedAXNode
from .target import Target
from .touch_handle import TouchHandle
from .touchscreen import Touchscreen
from .tracing import Tracing
from .web_mcp import WebMCP
from .web_mcp_tool import WebMCPTool
from .web_worker import WebWorker
from .writable_destination import WritableDestination

PUPPETEER_VERSION = "25.12.0"

__all__ = [
    "PUPPETEER_VERSION",
    "Accessibility",
    "BluetoothEmulation",
    "Browser",
    "BrowserContext",
    "BrowserLauncher",
    "CDPSession",
    "CSSCoverage",
    "CommonEventEmitter",
    "Connection",
    "ConnectionClosedError",
    "ConnectionTransport",
    "ConsoleMessage",
    "Coverage",
    "DeviceRequestPrompt",
    "Dialog",
    "ElementHandle",
    "EventEmitter",
    "Extension",
    "ExtensionTransport",
    "FileChooser",
    "Frame",
    "HTTPRequest",
    "HTTPResponse",
    "JSCoverage",
    "JSHandle",
    "Keyboard",
    "Locator",
    "Mouse",
    "Moveable",
    "Page",
    "ProtocolError",
    "Puppeteer",
    "PuppeteerError",
    "PuppeteerNode",
    "Realm",
    "ScreenRecorder",
    "ScreenRecording",
    "SecurityDetails",
    "SerializedAXNode",
    "Target",
    "TouchHandle",
    "Touchscreen",
    "Tracing",
    "WebMCP",
    "WebMCPTool",
    "WebWorker",
    "WritableDestination",
]
