# @generated by scripts/generate-puppeteer-bindings.mjs from
# rust/protocol/puppeteer/api.json. Do not edit by hand.
# mypy: disable-error-code="override"
"""Puppeteer's ``BrowserLauncher`` (puppeteer-core 25.12.0)."""

from __future__ import annotations

from typing import TYPE_CHECKING, Any

from ..bridge import RemoteObject, _opt

if TYPE_CHECKING:
    from .browser import Browser


class BrowserLauncher(RemoteObject):
    """Puppeteer's ``BrowserLauncher``, a remote object served by ``serve --stdio``."""

    TYPE = "BrowserLauncher"

    async def browser(self) -> str:
        """``BrowserLauncher.browser``.

        .. code-block:: typescript

            get browser(): SupportedBrowser
        """
        return await self._get("browser", "string")

    async def launch(self, options: Any | None = None) -> Browser:
        """``BrowserLauncher.launch``.

        .. code-block:: typescript

            launch(options?: LaunchOptions): Promise<Browser>
        """
        return await self._call("launch", [_opt(options)], "handle:Browser")

    async def executable_path(self, channel: str | None = None, validate_path: bool | None = None) -> str:
        """``BrowserLauncher.executablePath``.

        .. code-block:: typescript

            executablePath(channel?: ChromeReleaseChannel, validatePath?: boolean): Promise<string>
        """
        return await self._call("executablePath", [_opt(channel), _opt(validate_path)], "string")

    async def default_args(self, object: Any) -> list[str]:
        """``BrowserLauncher.defaultArgs``.

        .. code-block:: typescript

            defaultArgs(object: LaunchOptions): string[]
        """
        return await self._call("defaultArgs", [object], "list:string")
