# @generated by scripts/generate-puppeteer-bindings.mjs from
# rust/protocol/puppeteer/api.json. Do not edit by hand.
# mypy: disable-error-code="override"
"""Puppeteer's ``ConnectionTransport`` (puppeteer-core 25.12.0)."""

from __future__ import annotations

from ..bridge import RemoteObject


class ConnectionTransport(RemoteObject):
    """Puppeteer's ``ConnectionTransport``, a remote object served by ``serve --stdio``."""

    TYPE = "ConnectionTransport"

    async def send(self, message: str) -> None:
        """``ConnectionTransport.send``.

        .. code-block:: typescript

            send(message: string): void
        """
        return await self._call("send", [message], "void")

    async def close(self) -> None:
        """``ConnectionTransport.close``.

        .. code-block:: typescript

            close(): void
        """
        return await self._call("close", [], "void")
