# @generated by scripts/generate-puppeteer-bindings.mjs from
# rust/protocol/puppeteer/api.json. Do not edit by hand.
# mypy: disable-error-code="override"
"""Puppeteer's ``ConnectionClosedError`` (puppeteer-core 25.12.0)."""

from __future__ import annotations

from .protocol_error import ProtocolError


class ConnectionClosedError(ProtocolError):
    """Puppeteer's ``ConnectionClosedError``, a remote object served by ``serve --stdio``."""

    TYPE = "ConnectionClosedError"
