# @generated by scripts/generate-puppeteer-bindings.mjs from
# rust/protocol/puppeteer/api.json. Do not edit by hand.
# mypy: disable-error-code="override"
"""Puppeteer's ``ConsoleMessage`` (puppeteer-core 25.10.0)."""

from __future__ import annotations

from typing import TYPE_CHECKING, Any

from ..bridge import RemoteObject

if TYPE_CHECKING:
    from .js_handle import JSHandle


class ConsoleMessage(RemoteObject):
    """Puppeteer's ``ConsoleMessage``, a remote object served by ``serve --stdio``."""

    TYPE = "ConsoleMessage"

    async def type(self) -> str:
        """``ConsoleMessage.type``.

        .. code-block:: typescript

            type(): ConsoleMessageType
        """
        return await self._call("type", [], "string")

    async def text(self) -> str:
        """``ConsoleMessage.text``.

        .. code-block:: typescript

            text(): string
        """
        return await self._call("text", [], "string")

    async def args(self) -> list[JSHandle]:
        """``ConsoleMessage.args``.

        .. code-block:: typescript

            args(): JSHandle[]
        """
        return await self._call("args", [], "list:handle:JSHandle")

    async def location(self) -> Any:
        """``ConsoleMessage.location``.

        .. code-block:: typescript

            location(): ConsoleMessageLocation
        """
        return await self._call("location", [], "json")

    async def stack_trace(self) -> list[Any]:
        """``ConsoleMessage.stackTrace``.

        .. code-block:: typescript

            stackTrace(): ConsoleMessageLocation[]
        """
        return await self._call("stackTrace", [], "list:json")
