# @generated by scripts/generate-puppeteer-bindings.mjs from
# rust/protocol/puppeteer/api.json. Do not edit by hand.
# mypy: disable-error-code="override"
"""Puppeteer's ``CSSCoverage`` (puppeteer-core 25.10.0)."""

from __future__ import annotations

from typing import Any

from ..bridge import RemoteObject, _opt


class CSSCoverage(RemoteObject):
    """Puppeteer's ``CSSCoverage``, a remote object served by ``serve --stdio``."""

    TYPE = "CSSCoverage"

    async def start(self, options: Any | None = None) -> None:
        """``CSSCoverage.start``.

        .. code-block:: typescript

            start(options?: {resetOnNavigation?: boolean}): Promise<void>
        """
        return await self._call("start", [_opt(options)], "void")

    async def stop(self) -> list[Any]:
        """``CSSCoverage.stop``.

        .. code-block:: typescript

            stop(): Promise<CoverageEntry[]>
        """
        return await self._call("stop", [], "list:json")
