# @generated by scripts/generate-puppeteer-bindings.mjs from
# rust/protocol/puppeteer/api.json. Do not edit by hand.
# mypy: disable-error-code="override"
"""Puppeteer's ``DeviceRequestPrompt`` (puppeteer-core 25.10.0)."""

from __future__ import annotations

from typing import Any

from ..bridge import JsFunction, RemoteObject, _opt


class DeviceRequestPrompt(RemoteObject):
    """Puppeteer's ``DeviceRequestPrompt``, a remote object served by ``serve --stdio``."""

    TYPE = "DeviceRequestPrompt"

    async def wait_for_device(self, filter: str | JsFunction, options: Any | None = None) -> Any:
        """``DeviceRequestPrompt.waitForDevice``.

        .. code-block:: typescript

            waitForDevice(filter: (device: DeviceRequestPromptDevice) => boolean, options?: WaitTimeoutOptions): Promise<DeviceRequestPromptDevice>
        """
        return await self._call("waitForDevice", [filter, _opt(options)], "json")

    async def select(self, device: Any) -> None:
        """``DeviceRequestPrompt.select``.

        .. code-block:: typescript

            select(device: DeviceRequestPromptDevice): Promise<void>
        """
        return await self._call("select", [device], "void")

    async def cancel(self) -> None:
        """``DeviceRequestPrompt.cancel``.

        .. code-block:: typescript

            cancel(): Promise<void>
        """
        return await self._call("cancel", [], "void")
