# @generated by scripts/generate-puppeteer-bindings.mjs from
# rust/protocol/puppeteer/api.json. Do not edit by hand.
# mypy: disable-error-code="override"
"""Puppeteer's ``Dialog`` (puppeteer-core 25.10.0)."""

from __future__ import annotations

from typing import Any

from ..bridge import RemoteObject, _opt


class Dialog(RemoteObject):
    """Puppeteer's ``Dialog``, a remote object served by ``serve --stdio``."""

    TYPE = "Dialog"

    async def handled(self) -> bool:
        """``Dialog.handled``.

        .. code-block:: typescript

            get handled(): boolean
        """
        return await self._get("handled", "boolean")

    async def type(self) -> Any:
        """``Dialog.type``.

        .. code-block:: typescript

            type(): Protocol.Page.DialogType
        """
        return await self._call("type", [], "json")

    async def message(self) -> str:
        """``Dialog.message``.

        .. code-block:: typescript

            message(): string
        """
        return await self._call("message", [], "string")

    async def default_value(self) -> str:
        """``Dialog.defaultValue``.

        .. code-block:: typescript

            defaultValue(): string
        """
        return await self._call("defaultValue", [], "string")

    async def accept(self, prompt_text: str | None = None) -> None:
        """``Dialog.accept``.

        .. code-block:: typescript

            accept(promptText?: string): Promise<void>
        """
        return await self._call("accept", [_opt(prompt_text)], "void")

    async def dismiss(self) -> None:
        """``Dialog.dismiss``.

        .. code-block:: typescript

            dismiss(): Promise<void>
        """
        return await self._call("dismiss", [], "void")
