# @generated by scripts/generate-puppeteer-bindings.mjs from
# rust/protocol/puppeteer/api.json. Do not edit by hand.
# mypy: disable-error-code="override"
"""Puppeteer's ``EventEmitter`` (puppeteer-core 25.12.0)."""

from __future__ import annotations

from typing import Any

from ..bridge import JsFunction, RemoteObject, _opt


class EventEmitter(RemoteObject):
    """Puppeteer's ``EventEmitter``, a remote object served by ``serve --stdio``."""

    TYPE = "EventEmitter"

    async def on(self, type: Any, handler: str | JsFunction) -> EventEmitter:
        """``EventEmitter.on``.

        .. code-block:: typescript

            on<Key extends keyof EventsWithWildcard<Events>>(type: Key, handler: Handler<EventsWithWildcard<Events>[Key]>): this
        """
        return await self._call("on", [type, handler], "handle:EventEmitter")

    async def off(self, type: Any, handler: str | JsFunction | None = None) -> EventEmitter:
        """``EventEmitter.off``.

        .. code-block:: typescript

            off<Key extends keyof EventsWithWildcard<Events>>(type: Key, handler?: Handler<EventsWithWildcard<Events>[Key]>): this
        """
        return await self._call("off", [type, _opt(handler)], "handle:EventEmitter")

    async def emit(self, type: Any, event: Any) -> bool:
        """``EventEmitter.emit``.

        .. code-block:: typescript

            emit<Key extends keyof EventsWithWildcard<Events>>(type: Key, event: EventsWithWildcard<Events>[Key]): boolean
        """
        return await self._call("emit", [type, event], "boolean")

    async def once(self, type: Any, handler: str | JsFunction) -> EventEmitter:
        """``EventEmitter.once``.

        .. code-block:: typescript

            once<Key extends keyof EventsWithWildcard<Events>>(type: Key, handler: Handler<EventsWithWildcard<Events>[Key]>): this
        """
        return await self._call("once", [type, handler], "handle:EventEmitter")

    async def listener_count(self, type: Any) -> float:
        """``EventEmitter.listenerCount``.

        .. code-block:: typescript

            listenerCount(type: keyof EventsWithWildcard<Events>): number
        """
        return await self._call("listenerCount", [type], "number")

    async def remove_all_listeners(self, type: Any | None = None) -> EventEmitter:
        """``EventEmitter.removeAllListeners``.

        .. code-block:: typescript

            removeAllListeners(type?: keyof EventsWithWildcard<Events>): this
        """
        return await self._call("removeAllListeners", [_opt(type)], "handle:EventEmitter")
