# @generated by scripts/generate-puppeteer-bindings.mjs from
# rust/protocol/puppeteer/api.json. Do not edit by hand.
# mypy: disable-error-code="override"
"""Puppeteer's ``HTTPRequest`` (puppeteer-core 25.10.0)."""

from __future__ import annotations

from typing import TYPE_CHECKING, Any

from ..bridge import JsFunction, RemoteObject, _opt

if TYPE_CHECKING:
    from .cdp_session import CDPSession
    from .frame import Frame
    from .http_response import HTTPResponse


class HTTPRequest(RemoteObject):
    """Puppeteer's ``HTTPRequest``, a remote object served by ``serve --stdio``."""

    TYPE = "HTTPRequest"

    async def client(self) -> CDPSession:
        """``HTTPRequest.client``.

        .. code-block:: typescript

            get client(): CDPSession
        """
        return await self._get("client", "handle:CDPSession")

    async def url(self) -> str:
        """``HTTPRequest.url``.

        .. code-block:: typescript

            url(): string
        """
        return await self._call("url", [], "string")

    async def continue_request_overrides(self) -> Any:
        """``HTTPRequest.continueRequestOverrides``.

        .. code-block:: typescript

            continueRequestOverrides(): ContinueRequestOverrides
        """
        return await self._call("continueRequestOverrides", [], "json")

    async def response_for_request(self) -> Any | None:
        """``HTTPRequest.responseForRequest``.

        .. code-block:: typescript

            responseForRequest(): Partial<ResponseForRequest> | null
        """
        return await self._call("responseForRequest", [], "json?")

    async def abort_error_reason(self) -> Any | None:
        """``HTTPRequest.abortErrorReason``.

        .. code-block:: typescript

            abortErrorReason(): Protocol.Network.ErrorReason | null
        """
        return await self._call("abortErrorReason", [], "json?")

    async def intercept_resolution_state(self) -> Any:
        """``HTTPRequest.interceptResolutionState``.

        .. code-block:: typescript

            interceptResolutionState(): InterceptResolutionState
        """
        return await self._call("interceptResolutionState", [], "json")

    async def is_intercept_resolution_handled(self) -> bool:
        """``HTTPRequest.isInterceptResolutionHandled``.

        .. code-block:: typescript

            isInterceptResolutionHandled(): boolean
        """
        return await self._call("isInterceptResolutionHandled", [], "boolean")

    async def enqueue_intercept_action(self, pending_handler: str | JsFunction) -> None:
        """``HTTPRequest.enqueueInterceptAction``.

        .. code-block:: typescript

            enqueueInterceptAction(pendingHandler: () => void | PromiseLike<unknown>): void
        """
        return await self._call("enqueueInterceptAction", [pending_handler], "void")

    async def finalize_interceptions(self) -> None:
        """``HTTPRequest.finalizeInterceptions``.

        .. code-block:: typescript

            finalizeInterceptions(): Promise<void>
        """
        return await self._call("finalizeInterceptions", [], "void")

    async def resource_type(self) -> Any:
        """``HTTPRequest.resourceType``.

        .. code-block:: typescript

            resourceType(): ResourceType
        """
        return await self._call("resourceType", [], "json")

    async def method(self) -> str:
        """``HTTPRequest.method``.

        .. code-block:: typescript

            method(): string
        """
        return await self._call("method", [], "string")

    async def post_data(self) -> str | None:
        """``HTTPRequest.postData``.

        .. code-block:: typescript

            postData(): string | undefined
        """
        return await self._call("postData", [], "string?")

    async def has_post_data(self) -> bool:
        """``HTTPRequest.hasPostData``.

        .. code-block:: typescript

            hasPostData(): boolean
        """
        return await self._call("hasPostData", [], "boolean")

    async def fetch_post_data(self) -> str | None:
        """``HTTPRequest.fetchPostData``.

        .. code-block:: typescript

            fetchPostData(): Promise<string | undefined>
        """
        return await self._call("fetchPostData", [], "string?")

    async def headers(self) -> Any:
        """``HTTPRequest.headers``.

        .. code-block:: typescript

            headers(): Record<string, string>
        """
        return await self._call("headers", [], "json")

    async def response(self) -> HTTPResponse | None:
        """``HTTPRequest.response``.

        .. code-block:: typescript

            response(): HTTPResponse | null
        """
        return await self._call("response", [], "handle:HTTPResponse?")

    async def frame(self) -> Frame | None:
        """``HTTPRequest.frame``.

        .. code-block:: typescript

            frame(): Frame | null
        """
        return await self._call("frame", [], "handle:Frame?")

    async def is_navigation_request(self) -> bool:
        """``HTTPRequest.isNavigationRequest``.

        .. code-block:: typescript

            isNavigationRequest(): boolean
        """
        return await self._call("isNavigationRequest", [], "boolean")

    async def initiator(self) -> Any | None:
        """``HTTPRequest.initiator``.

        .. code-block:: typescript

            initiator(): Protocol.Network.Initiator | undefined
        """
        return await self._call("initiator", [], "json?")

    async def redirect_chain(self) -> list[HTTPRequest]:
        """``HTTPRequest.redirectChain``.

        .. code-block:: typescript

            redirectChain(): HTTPRequest[]
        """
        return await self._call("redirectChain", [], "list:handle:HTTPRequest")

    async def failure(self) -> Any | None:
        """``HTTPRequest.failure``.

        .. code-block:: typescript

            failure(): { errorText: string; } | null
        """
        return await self._call("failure", [], "json?")

    async def continue_(self, overrides: Any | None = None, priority: float | None = None) -> None:
        """``HTTPRequest.continue``.

        .. code-block:: typescript

            continue(overrides?: ContinueRequestOverrides, priority?: number): Promise<void>
        """
        return await self._call("continue", [_opt(overrides), _opt(priority)], "void")

    async def respond(self, response: Any, priority: float | None = None) -> None:
        """``HTTPRequest.respond``.

        .. code-block:: typescript

            respond(response: Partial<ResponseForRequest>, priority?: number): Promise<void>
        """
        return await self._call("respond", [response, _opt(priority)], "void")

    async def abort(self, error_code: str | None = None, priority: float | None = None) -> None:
        """``HTTPRequest.abort``.

        .. code-block:: typescript

            abort(errorCode?: ErrorCode, priority?: number): Promise<void>
        """
        return await self._call("abort", [_opt(error_code), _opt(priority)], "void")
