# @generated by scripts/generate-puppeteer-bindings.mjs from
# rust/protocol/puppeteer/api.json. Do not edit by hand.
# mypy: disable-error-code="override"
"""Puppeteer's ``Keyboard`` (puppeteer-core 25.12.0)."""

from __future__ import annotations

from typing import Any

from ..bridge import RemoteObject, _opt


class Keyboard(RemoteObject):
    """Puppeteer's ``Keyboard``, a remote object served by ``serve --stdio``."""

    TYPE = "Keyboard"

    async def down(self, key: str, options: Any | None = None) -> None:
        """``Keyboard.down``.

        .. code-block:: typescript

            down(key: KeyInput, options?: Readonly<KeyDownOptions>): Promise<void>
        """
        return await self._call("down", [key, _opt(options)], "void")

    async def up(self, key: str) -> None:
        """``Keyboard.up``.

        .. code-block:: typescript

            up(key: KeyInput): Promise<void>
        """
        return await self._call("up", [key], "void")

    async def send_character(self, char: str) -> None:
        """``Keyboard.sendCharacter``.

        .. code-block:: typescript

            sendCharacter(char: string): Promise<void>
        """
        return await self._call("sendCharacter", [char], "void")

    async def type(self, text: str, options: Any | None = None) -> None:
        """``Keyboard.type``.

        .. code-block:: typescript

            type(text: string, options?: Readonly<KeyboardTypeOptions>): Promise<void>
        """
        return await self._call("type", [text, _opt(options)], "void")

    async def press(self, key: str, options: Any | None = None) -> None:
        """``Keyboard.press``.

        .. code-block:: typescript

            press(key: KeyInput, options?: Readonly<KeyPressOptions>): Promise<void>
        """
        return await self._call("press", [key, _opt(options)], "void")
