# @generated by scripts/generate-puppeteer-bindings.mjs from
# rust/protocol/puppeteer/api.json. Do not edit by hand.
# mypy: disable-error-code="override"
"""Puppeteer's ``Mouse`` (puppeteer-core 25.10.0)."""

from __future__ import annotations

from typing import Any

from ..bridge import RemoteObject, _opt


class Mouse(RemoteObject):
    """Puppeteer's ``Mouse``, a remote object served by ``serve --stdio``."""

    TYPE = "Mouse"

    async def reset(self) -> None:
        """``Mouse.reset``.

        .. code-block:: typescript

            reset(): Promise<void>
        """
        return await self._call("reset", [], "void")

    async def move(self, x: float, y: float, options: Any | None = None) -> None:
        """``Mouse.move``.

        .. code-block:: typescript

            move(x: number, y: number, options?: Readonly<MouseMoveOptions>): Promise<void>
        """
        return await self._call("move", [x, y, _opt(options)], "void")

    async def down(self, options: Any | None = None) -> None:
        """``Mouse.down``.

        .. code-block:: typescript

            down(options?: Readonly<MouseOptions>): Promise<void>
        """
        return await self._call("down", [_opt(options)], "void")

    async def up(self, options: Any | None = None) -> None:
        """``Mouse.up``.

        .. code-block:: typescript

            up(options?: Readonly<MouseOptions>): Promise<void>
        """
        return await self._call("up", [_opt(options)], "void")

    async def click(self, x: float, y: float, options: Any | None = None) -> None:
        """``Mouse.click``.

        .. code-block:: typescript

            click(x: number, y: number, options?: Readonly<MouseClickOptions>): Promise<void>
        """
        return await self._call("click", [x, y, _opt(options)], "void")

    async def wheel(self, options: Any | None = None) -> None:
        """``Mouse.wheel``.

        .. code-block:: typescript

            wheel(options?: Readonly<MouseWheelOptions>): Promise<void>
        """
        return await self._call("wheel", [_opt(options)], "void")

    async def drag(self, start: Any, target: Any) -> Any:
        """``Mouse.drag``.

        .. code-block:: typescript

            drag(start: Point, target: Point): Promise<Protocol.Input.DragData>
        """
        return await self._call("drag", [start, target], "json")

    async def drag_enter(self, target: Any, data: Any) -> None:
        """``Mouse.dragEnter``.

        .. code-block:: typescript

            dragEnter(target: Point, data: Protocol.Input.DragData): Promise<void>
        """
        return await self._call("dragEnter", [target, data], "void")

    async def drag_over(self, target: Any, data: Any) -> None:
        """``Mouse.dragOver``.

        .. code-block:: typescript

            dragOver(target: Point, data: Protocol.Input.DragData): Promise<void>
        """
        return await self._call("dragOver", [target, data], "void")

    async def drop(self, target: Any, data: Any) -> None:
        """``Mouse.drop``.

        .. code-block:: typescript

            drop(target: Point, data: Protocol.Input.DragData): Promise<void>
        """
        return await self._call("drop", [target, data], "void")

    async def drag_and_drop(self, start: Any, target: Any, options: Any | None = None) -> None:
        """``Mouse.dragAndDrop``.

        .. code-block:: typescript

            dragAndDrop(start: Point, target: Point, options?: { delay?: number; }): Promise<void>
        """
        return await self._call("dragAndDrop", [start, target, _opt(options)], "void")
