# @generated by scripts/generate-puppeteer-bindings.mjs from
# rust/protocol/puppeteer/api.json. Do not edit by hand.
# mypy: disable-error-code="override"
"""Puppeteer's ``Moveable`` (puppeteer-core 25.12.0)."""

from __future__ import annotations

from ..bridge import RemoteObject


class Moveable(RemoteObject):
    """Puppeteer's ``Moveable``, a remote object served by ``serve --stdio``."""

    TYPE = "Moveable"

    async def move(self) -> Moveable:
        """``Moveable.move``.

        .. code-block:: typescript

            move(): this
        """
        return await self._call("move", [], "handle:Moveable")
