# @generated by scripts/generate-puppeteer-bindings.mjs from
# rust/protocol/puppeteer/api.json. Do not edit by hand.
# mypy: disable-error-code="override"
"""Puppeteer's ``Page`` (puppeteer-core 25.10.0)."""

from __future__ import annotations

from typing import TYPE_CHECKING, Any

from ..bridge import JsFunction, _opt
from .event_emitter import EventEmitter

if TYPE_CHECKING:
    from .accessibility import Accessibility
    from .bluetooth_emulation import BluetoothEmulation
    from .browser import Browser
    from .browser_context import BrowserContext
    from .cdp_session import CDPSession
    from .coverage import Coverage
    from .device_request_prompt import DeviceRequestPrompt
    from .element_handle import ElementHandle
    from .extension import Extension
    from .file_chooser import FileChooser
    from .frame import Frame
    from .http_request import HTTPRequest
    from .http_response import HTTPResponse
    from .js_handle import JSHandle
    from .keyboard import Keyboard
    from .locator import Locator
    from .mouse import Mouse
    from .realm import Realm
    from .screen_recorder import ScreenRecorder
    from .screen_recording import ScreenRecording
    from .target import Target
    from .touchscreen import Touchscreen
    from .tracing import Tracing
    from .web_mcp import WebMCP
    from .web_worker import WebWorker


class Page(EventEmitter):
    """Puppeteer's ``Page``, a remote object served by ``serve --stdio``."""

    TYPE = "Page"

    async def is_service_worker_bypassed(self) -> bool:
        """``Page.isServiceWorkerBypassed``.

        .. code-block:: typescript

            isServiceWorkerBypassed(): boolean
        """
        return await self._call("isServiceWorkerBypassed", [], "boolean")

    async def is_drag_interception_enabled(self) -> bool:
        """``Page.isDragInterceptionEnabled``.

        .. code-block:: typescript

            isDragInterceptionEnabled(): boolean
        """
        return await self._call("isDragInterceptionEnabled", [], "boolean")

    async def is_java_script_enabled(self) -> bool:
        """``Page.isJavaScriptEnabled``.

        .. code-block:: typescript

            isJavaScriptEnabled(): boolean
        """
        return await self._call("isJavaScriptEnabled", [], "boolean")

    async def wait_for_file_chooser(self, options: Any | None = None) -> FileChooser:
        """``Page.waitForFileChooser``.

        .. code-block:: typescript

            waitForFileChooser(options?: WaitTimeoutOptions): Promise<FileChooser>
        """
        return await self._call("waitForFileChooser", [_opt(options)], "handle:FileChooser")

    async def set_geolocation(self, options: Any) -> None:
        """``Page.setGeolocation``.

        .. code-block:: typescript

            setGeolocation(options: GeolocationOptions): Promise<void>
        """
        return await self._call("setGeolocation", [options], "void")

    async def target(self) -> Target:
        """``Page.target``.

        .. code-block:: typescript

            target(): Target
        """
        return await self._call("target", [], "handle:Target")

    async def browser(self) -> Browser:
        """``Page.browser``.

        .. code-block:: typescript

            browser(): Browser
        """
        return await self._call("browser", [], "handle:Browser")

    async def browser_context(self) -> BrowserContext:
        """``Page.browserContext``.

        .. code-block:: typescript

            browserContext(): BrowserContext
        """
        return await self._call("browserContext", [], "handle:BrowserContext")

    async def main_frame(self) -> Frame:
        """``Page.mainFrame``.

        .. code-block:: typescript

            mainFrame(): Frame
        """
        return await self._call("mainFrame", [], "handle:Frame")

    async def create_cdp_session(self) -> CDPSession:
        """``Page.createCDPSession``.

        .. code-block:: typescript

            createCDPSession(): Promise<CDPSession>
        """
        return await self._call("createCDPSession", [], "handle:CDPSession")

    async def keyboard(self) -> Keyboard:
        """``Page.keyboard``.

        .. code-block:: typescript

            get keyboard(): Keyboard
        """
        return await self._get("keyboard", "handle:Keyboard")

    async def touchscreen(self) -> Touchscreen:
        """``Page.touchscreen``.

        .. code-block:: typescript

            get touchscreen(): Touchscreen
        """
        return await self._get("touchscreen", "handle:Touchscreen")

    async def coverage(self) -> Coverage:
        """``Page.coverage``.

        .. code-block:: typescript

            get coverage(): Coverage
        """
        return await self._get("coverage", "handle:Coverage")

    async def tracing(self) -> Tracing:
        """``Page.tracing``.

        .. code-block:: typescript

            get tracing(): Tracing
        """
        return await self._get("tracing", "handle:Tracing")

    async def webmcp(self) -> WebMCP:
        """``Page.webmcp``.

        .. code-block:: typescript

            get webmcp(): WebMCP
        """
        return await self._get("webmcp", "handle:WebMCP")

    async def accessibility(self) -> Accessibility:
        """``Page.accessibility``.

        .. code-block:: typescript

            get accessibility(): Accessibility
        """
        return await self._get("accessibility", "handle:Accessibility")

    async def frames(self) -> list[Frame]:
        """``Page.frames``.

        .. code-block:: typescript

            frames(): Frame[]
        """
        return await self._call("frames", [], "list:handle:Frame")

    async def workers(self) -> list[WebWorker]:
        """``Page.workers``.

        .. code-block:: typescript

            workers(): WebWorker[]
        """
        return await self._call("workers", [], "list:handle:WebWorker")

    async def set_request_interception(self, value: bool) -> None:
        """``Page.setRequestInterception``.

        .. code-block:: typescript

            setRequestInterception(value: boolean): Promise<void>
        """
        return await self._call("setRequestInterception", [value], "void")

    async def set_bypass_service_worker(self, bypass: bool) -> None:
        """``Page.setBypassServiceWorker``.

        .. code-block:: typescript

            setBypassServiceWorker(bypass: boolean): Promise<void>
        """
        return await self._call("setBypassServiceWorker", [bypass], "void")

    async def set_drag_interception(self, enabled: bool) -> None:
        """``Page.setDragInterception``.

        .. code-block:: typescript

            setDragInterception(enabled: boolean): Promise<void>
        """
        return await self._call("setDragInterception", [enabled], "void")

    async def set_offline_mode(self, enabled: bool) -> None:
        """``Page.setOfflineMode``.

        .. code-block:: typescript

            setOfflineMode(enabled: boolean): Promise<void>
        """
        return await self._call("setOfflineMode", [enabled], "void")

    async def emulate_network_conditions(self, network_conditions: Any | None) -> None:
        """``Page.emulateNetworkConditions``.

        .. code-block:: typescript

            emulateNetworkConditions(networkConditions: NetworkConditions | null): Promise<void>
        """
        return await self._call("emulateNetworkConditions", [network_conditions], "void")

    async def set_default_navigation_timeout(self, timeout: float) -> None:
        """``Page.setDefaultNavigationTimeout``.

        .. code-block:: typescript

            setDefaultNavigationTimeout(timeout: number): void
        """
        return await self._call("setDefaultNavigationTimeout", [timeout], "void")

    async def set_default_timeout(self, timeout: float) -> None:
        """``Page.setDefaultTimeout``.

        .. code-block:: typescript

            setDefaultTimeout(timeout: number): void
        """
        return await self._call("setDefaultTimeout", [timeout], "void")

    async def get_default_timeout(self) -> float:
        """``Page.getDefaultTimeout``.

        .. code-block:: typescript

            getDefaultTimeout(): number
        """
        return await self._call("getDefaultTimeout", [], "number")

    async def get_default_navigation_timeout(self) -> float:
        """``Page.getDefaultNavigationTimeout``.

        .. code-block:: typescript

            getDefaultNavigationTimeout(): number
        """
        return await self._call("getDefaultNavigationTimeout", [], "number")

    async def locator(self, selector: str | JsFunction) -> Locator:
        """``Page.locator``.

        .. code-block:: typescript

            locator<Selector extends string>(selector: Selector): Locator<NodeFor<Selector>>
            locator<Ret>(func: () => Awaitable<Ret>): Locator<Ret>
        """
        return await self._call("locator", [selector], "handle:Locator")

    async def query_selector(self, selector: str) -> ElementHandle | None:
        """``Page.$``.

        .. code-block:: typescript

            $<Selector extends string>(selector: Selector): Promise<ElementHandle<NodeFor<Selector>> | null>
        """
        return await self._call("$", [selector], "handle:ElementHandle?")

    async def query_selector_all(self, selector: str, options: Any | None = None) -> list[ElementHandle]:
        """``Page.$$``.

        .. code-block:: typescript

            $$<Selector extends string>(selector: Selector, options?: QueryOptions): Promise<Array<ElementHandle<NodeFor<Selector>>>>
        """
        return await self._call("$$", [selector, _opt(options)], "list:handle:ElementHandle")

    async def evaluate_handle(self, page_function: str | JsFunction, *args: Any) -> JSHandle:
        """``Page.evaluateHandle``.

        .. code-block:: typescript

            evaluateHandle<Params extends unknown[], Func extends EvaluateFunc<Params> = EvaluateFunc<Params>>(pageFunction: Func | string, ...args: Params ): Promise<HandleFor<Awaited<ReturnType<Func>>>>
        """
        return await self._call("evaluateHandle", [page_function, *args], "handle:JSHandle")

    async def query_objects(self, prototype_handle: JSHandle) -> JSHandle:
        """``Page.queryObjects``.

        .. code-block:: typescript

            queryObjects<Prototype>(prototypeHandle: JSHandle<Prototype>): Promise<JSHandle<Prototype[]>>
        """
        return await self._call("queryObjects", [prototype_handle], "handle:JSHandle")

    async def eval_on_selector(self, selector: str, page_function: str | JsFunction, *args: Any) -> Any:
        """``Page.$eval``.

        .. code-block:: typescript

            $eval<Selector extends string, Params extends unknown[], Func extends EvaluateFuncWith<NodeFor<Selector>, Params> = EvaluateFuncWith<NodeFor<Selector>, Params >>(selector: Selector, pageFunction: Func | string, ...args: Params ): Promise<Awaited<ReturnType<Func>>>
        """
        return await self._call("$eval", [selector, page_function, *args], "json")

    async def eval_on_selector_all(self, selector: str, page_function: str | JsFunction, *args: Any) -> Any:
        """``Page.$$eval``.

        .. code-block:: typescript

            $$eval<Selector extends string, Params extends unknown[], Func extends EvaluateFuncWith<Array<NodeFor<Selector>>, Params> = EvaluateFuncWith<Array<NodeFor<Selector>>, Params>>(selector: Selector, pageFunction: Func | string, ...args: Params ): Promise<Awaited<ReturnType<Func>>>
        """
        return await self._call("$$eval", [selector, page_function, *args], "json")

    async def cookies(self, *urls: str) -> list[Any]:
        """``Page.cookies``.

        .. code-block:: typescript

            cookies(...urls: string[]): Promise<Cookie[]>
        """
        return await self._call("cookies", [*urls], "list:json")

    async def delete_cookie(self, *cookies: Any) -> None:
        """``Page.deleteCookie``.

        .. code-block:: typescript

            deleteCookie(...cookies: DeleteCookiesRequest[]): Promise<void>
        """
        return await self._call("deleteCookie", [*cookies], "void")

    async def set_cookie(self, *cookies: Any) -> None:
        """``Page.setCookie``.

        .. code-block:: typescript

            setCookie(...cookies: CookieParam[]): Promise<void>
        """
        return await self._call("setCookie", [*cookies], "void")

    async def add_script_tag(self, options: Any) -> ElementHandle:
        """``Page.addScriptTag``.

        .. code-block:: typescript

            addScriptTag(options: FrameAddScriptTagOptions): Promise<ElementHandle<HTMLScriptElement>>
        """
        return await self._call("addScriptTag", [options], "handle:ElementHandle")

    async def add_style_tag(self, options: Any) -> ElementHandle:
        """``Page.addStyleTag``.

        .. code-block:: typescript

            addStyleTag(options: Omit<FrameAddStyleTagOptions, 'url'>): Promise<ElementHandle<HTMLStyleElement>>
            addStyleTag(options: FrameAddStyleTagOptions): Promise<ElementHandle<HTMLLinkElement>>
        """
        return await self._call("addStyleTag", [options], "handle:ElementHandle")

    async def expose_function(self, name: str, pptr_function: Any) -> None:
        """``Page.exposeFunction``.

        .. code-block:: typescript

            exposeFunction(name: string, pptrFunction: | Function | { default: Function; }): Promise<void>
        """
        return await self._call("exposeFunction", [name, pptr_function], "void")

    async def remove_exposed_function(self, name: str) -> None:
        """``Page.removeExposedFunction``.

        .. code-block:: typescript

            removeExposedFunction(name: string): Promise<void>
        """
        return await self._call("removeExposedFunction", [name], "void")

    async def authenticate(self, credentials: Any | None) -> None:
        """``Page.authenticate``.

        .. code-block:: typescript

            authenticate(credentials: Credentials | null): Promise<void>
        """
        return await self._call("authenticate", [credentials], "void")

    async def set_extra_http_headers(self, headers: Any) -> None:
        """``Page.setExtraHTTPHeaders``.

        .. code-block:: typescript

            setExtraHTTPHeaders(headers: Record<string, string>): Promise<void>
        """
        return await self._call("setExtraHTTPHeaders", [headers], "void")

    async def set_user_agent(self, user_agent: Any, user_agent_metadata: Any | None = None) -> None:
        """``Page.setUserAgent``.

        .. code-block:: typescript

            setUserAgent(userAgent: string, userAgentMetadata?: Protocol.Emulation.UserAgentMetadata): Promise<void>
            setUserAgent(options: { userAgent?: string; userAgentMetadata?: Protocol.Emulation.UserAgentMetadata; platform?: string; }): Promise<void>
        """
        return await self._call("setUserAgent", [user_agent, _opt(user_agent_metadata)], "void")

    async def metrics(self) -> Any:
        """``Page.metrics``.

        .. code-block:: typescript

            metrics(): Promise<Metrics>
        """
        return await self._call("metrics", [], "json")

    async def capture_heap_snapshot(self, options: Any) -> None:
        """``Page.captureHeapSnapshot``.

        .. code-block:: typescript

            captureHeapSnapshot(options: HeapSnapshotOptions): Promise<void>
        """
        return await self._call("captureHeapSnapshot", [options], "void")

    async def url(self) -> str:
        """``Page.url``.

        .. code-block:: typescript

            url(): string
        """
        return await self._call("url", [], "string")

    async def content(self) -> str:
        """``Page.content``.

        .. code-block:: typescript

            content(): Promise<string>
        """
        return await self._call("content", [], "string")

    async def set_content(self, html: str, options: Any | None = None) -> None:
        """``Page.setContent``.

        .. code-block:: typescript

            setContent(html: string, options?: SetContentWaitForOptions): Promise<void>
        """
        return await self._call("setContent", [html, _opt(options)], "void")

    async def goto(self, url: str, options: Any | None = None) -> HTTPResponse | None:
        """``Page.goto``.

        .. code-block:: typescript

            goto(url: string, options?: GoToOptions): Promise<HTTPResponse | null>
        """
        return await self._call("goto", [url, _opt(options)], "handle:HTTPResponse?")

    async def reload(self, options: Any | None = None) -> HTTPResponse | None:
        """``Page.reload``.

        .. code-block:: typescript

            reload(options?: ReloadOptions): Promise<HTTPResponse | null>
        """
        return await self._call("reload", [_opt(options)], "handle:HTTPResponse?")

    async def wait_for_navigation(self, options: Any | None = None) -> HTTPResponse | None:
        """``Page.waitForNavigation``.

        .. code-block:: typescript

            waitForNavigation(options?: WaitForOptions): Promise<HTTPResponse | null>
        """
        return await self._call("waitForNavigation", [_opt(options)], "handle:HTTPResponse?")

    async def wait_for_request(self, url_or_predicate: str | JsFunction, options: Any | None = None) -> HTTPRequest:
        """``Page.waitForRequest``.

        .. code-block:: typescript

            waitForRequest(urlOrPredicate: string | AwaitablePredicate<HTTPRequest>, options?: WaitTimeoutOptions): Promise<HTTPRequest>
        """
        return await self._call("waitForRequest", [url_or_predicate, _opt(options)], "handle:HTTPRequest")

    async def wait_for_response(self, url_or_predicate: str | JsFunction, options: Any | None = None) -> HTTPResponse:
        """``Page.waitForResponse``.

        .. code-block:: typescript

            waitForResponse(urlOrPredicate: string | AwaitablePredicate<HTTPResponse>, options?: WaitTimeoutOptions): Promise<HTTPResponse>
        """
        return await self._call("waitForResponse", [url_or_predicate, _opt(options)], "handle:HTTPResponse")

    async def wait_for_network_idle(self, options: Any | None = None) -> None:
        """``Page.waitForNetworkIdle``.

        .. code-block:: typescript

            waitForNetworkIdle(options?: WaitForNetworkIdleOptions): Promise<void>
        """
        return await self._call("waitForNetworkIdle", [_opt(options)], "void")

    async def wait_for_frame(self, url_or_predicate: str | JsFunction, options: Any | None = None) -> Frame:
        """``Page.waitForFrame``.

        .. code-block:: typescript

            waitForFrame(urlOrPredicate: string | ((frame: Frame) => Awaitable<boolean>), options?: WaitTimeoutOptions): Promise<Frame>
        """
        return await self._call("waitForFrame", [url_or_predicate, _opt(options)], "handle:Frame")

    async def go_back(self, options: Any | None = None) -> HTTPResponse | None:
        """``Page.goBack``.

        .. code-block:: typescript

            goBack(options?: WaitForOptions): Promise<HTTPResponse | null>
        """
        return await self._call("goBack", [_opt(options)], "handle:HTTPResponse?")

    async def go_forward(self, options: Any | None = None) -> HTTPResponse | None:
        """``Page.goForward``.

        .. code-block:: typescript

            goForward(options?: WaitForOptions): Promise<HTTPResponse | null>
        """
        return await self._call("goForward", [_opt(options)], "handle:HTTPResponse?")

    async def bring_to_front(self) -> None:
        """``Page.bringToFront``.

        .. code-block:: typescript

            bringToFront(): Promise<void>
        """
        return await self._call("bringToFront", [], "void")

    async def emulate(self, device: Any) -> None:
        """``Page.emulate``.

        .. code-block:: typescript

            emulate(device: Device): Promise<void>
        """
        return await self._call("emulate", [device], "void")

    async def set_java_script_enabled(self, enabled: bool) -> None:
        """``Page.setJavaScriptEnabled``.

        .. code-block:: typescript

            setJavaScriptEnabled(enabled: boolean): Promise<void>
        """
        return await self._call("setJavaScriptEnabled", [enabled], "void")

    async def set_bypass_csp(self, enabled: bool) -> None:
        """``Page.setBypassCSP``.

        .. code-block:: typescript

            setBypassCSP(enabled: boolean): Promise<void>
        """
        return await self._call("setBypassCSP", [enabled], "void")

    async def emulate_media_type(self, type: str | None = None) -> None:
        """``Page.emulateMediaType``.

        .. code-block:: typescript

            emulateMediaType(type?: string): Promise<void>
        """
        return await self._call("emulateMediaType", [_opt(type)], "void")

    async def emulate_cpu_throttling(self, factor: float | None) -> None:
        """``Page.emulateCPUThrottling``.

        .. code-block:: typescript

            emulateCPUThrottling(factor: number | null): Promise<void>
        """
        return await self._call("emulateCPUThrottling", [factor], "void")

    async def emulate_media_features(self, features: list[Any] | None = None) -> None:
        """``Page.emulateMediaFeatures``.

        .. code-block:: typescript

            emulateMediaFeatures(features?: MediaFeature[]): Promise<void>
        """
        return await self._call("emulateMediaFeatures", [_opt(features)], "void")

    async def emulate_locale(self, locale: str | None = None) -> None:
        """``Page.emulateLocale``.

        .. code-block:: typescript

            emulateLocale(locale?: string): Promise<void>
        """
        return await self._call("emulateLocale", [_opt(locale)], "void")

    async def emulate_timezone(self, timezone_id: str | None = None) -> None:
        """``Page.emulateTimezone``.

        .. code-block:: typescript

            emulateTimezone(timezoneId?: string): Promise<void>
        """
        return await self._call("emulateTimezone", [_opt(timezone_id)], "void")

    async def emulate_idle_state(self, overrides: Any | None = None) -> None:
        """``Page.emulateIdleState``.

        .. code-block:: typescript

            emulateIdleState(overrides?: { isUserActive: boolean; isScreenUnlocked: boolean; }): Promise<void>
        """
        return await self._call("emulateIdleState", [_opt(overrides)], "void")

    async def emulate_vision_deficiency(self, type: Any | None = None) -> None:
        """``Page.emulateVisionDeficiency``.

        .. code-block:: typescript

            emulateVisionDeficiency(type?: Protocol.Emulation.SetEmulatedVisionDeficiencyRequest['type']): Promise<void>
        """
        return await self._call("emulateVisionDeficiency", [_opt(type)], "void")

    async def set_viewport(self, viewport: Any | None) -> None:
        """``Page.setViewport``.

        .. code-block:: typescript

            setViewport(viewport: Viewport | null): Promise<void>
        """
        return await self._call("setViewport", [viewport], "void")

    async def viewport(self) -> Any | None:
        """``Page.viewport``.

        .. code-block:: typescript

            viewport(): Viewport | null
        """
        return await self._call("viewport", [], "json?")

    async def evaluate(self, page_function: str | JsFunction, *args: Any) -> Any:
        """``Page.evaluate``.

        .. code-block:: typescript

            evaluate<Params extends unknown[], Func extends EvaluateFunc<Params> = EvaluateFunc<Params>>(pageFunction: Func | string, ...args: Params ): Promise<Awaited<ReturnType<Func>>>
        """
        return await self._call("evaluate", [page_function, *args], "json")

    async def evaluate_on_new_document(self, page_function: str | JsFunction, *args: Any) -> Any:
        """``Page.evaluateOnNewDocument``.

        .. code-block:: typescript

            evaluateOnNewDocument<Params extends unknown[], Func extends (...args: Params) => unknown = (...args: Params) => unknown>(pageFunction: Func | string, ...args: Params ): Promise<NewDocumentScriptEvaluation>
        """
        return await self._call("evaluateOnNewDocument", [page_function, *args], "json")

    async def remove_script_to_evaluate_on_new_document(self, identifier: str) -> None:
        """``Page.removeScriptToEvaluateOnNewDocument``.

        .. code-block:: typescript

            removeScriptToEvaluateOnNewDocument(identifier: string): Promise<void>
        """
        return await self._call("removeScriptToEvaluateOnNewDocument", [identifier], "void")

    async def set_cache_enabled(self, enabled: bool | None = None) -> None:
        """``Page.setCacheEnabled``.

        .. code-block:: typescript

            setCacheEnabled(enabled?: boolean): Promise<void>
        """
        return await self._call("setCacheEnabled", [_opt(enabled)], "void")

    async def screencast(self, options: Any | None = None) -> ScreenRecorder:
        """``Page.screencast``.

        .. code-block:: typescript

            screencast(options?: Readonly<ScreencastOptions>): Promise<ScreenRecorder>
        """
        return await self._call("screencast", [_opt(options)], "handle:ScreenRecorder")

    async def record(self, options: Any | None = None) -> ScreenRecording:
        """``Page.record``.

        .. code-block:: typescript

            record(options?: Readonly<RecordOptions>): Promise<ScreenRecording>
        """
        return await self._call("record", [_opt(options)], "handle:ScreenRecording")

    async def screenshot(self, options: Any | None = None) -> Any:
        """``Page.screenshot``.

        .. code-block:: typescript

            screenshot(options: Readonly<ScreenshotOptions> & { encoding: 'base64'; }): Promise<string>
            screenshot(options?: Readonly<ScreenshotOptions>): Promise<Uint8Array>
        """
        return await self._call("screenshot", [_opt(options)], "json")

    async def emulate_focused_page(self, enabled: bool) -> None:
        """``Page.emulateFocusedPage``.

        .. code-block:: typescript

            emulateFocusedPage(enabled: boolean): Promise<void>
        """
        return await self._call("emulateFocusedPage", [enabled], "void")

    async def create_pdf_stream(self, options: Any | None = None) -> Any:
        """``Page.createPDFStream``.

        .. code-block:: typescript

            createPDFStream(options?: PDFOptions): Promise<ReadableStream<Uint8Array>>
        """
        return await self._call("createPDFStream", [_opt(options)], "json")

    async def pdf(self, options: Any | None = None) -> bytes:
        """``Page.pdf``.

        .. code-block:: typescript

            pdf(options?: PDFOptions): Promise<Uint8Array>
        """
        return await self._call("pdf", [_opt(options)], "binary")

    async def title(self) -> str:
        """``Page.title``.

        .. code-block:: typescript

            title(): Promise<string>
        """
        return await self._call("title", [], "string")

    async def close(self, options: Any | None = None) -> None:
        """``Page.close``.

        .. code-block:: typescript

            close(options?: {runBeforeUnload?: boolean}): Promise<void>
        """
        return await self._call("close", [_opt(options)], "void")

    async def is_closed(self) -> bool:
        """``Page.isClosed``.

        .. code-block:: typescript

            isClosed(): boolean
        """
        return await self._call("isClosed", [], "boolean")

    async def mouse(self) -> Mouse:
        """``Page.mouse``.

        .. code-block:: typescript

            get mouse(): Mouse
        """
        return await self._get("mouse", "handle:Mouse")

    async def click(self, selector: str, options: Any | None = None) -> None:
        """``Page.click``.

        .. code-block:: typescript

            click(selector: string, options?: Readonly<ClickOptions>): Promise<void>
        """
        return await self._call("click", [selector, _opt(options)], "void")

    async def focus(self, selector: str) -> None:
        """``Page.focus``.

        .. code-block:: typescript

            focus(selector: string): Promise<void>
        """
        return await self._call("focus", [selector], "void")

    async def hover(self, selector: str) -> None:
        """``Page.hover``.

        .. code-block:: typescript

            hover(selector: string): Promise<void>
        """
        return await self._call("hover", [selector], "void")

    async def select(self, selector: str, *values: str) -> list[str]:
        """``Page.select``.

        .. code-block:: typescript

            select(selector: string, ...values: string[]): Promise<string[]>
        """
        return await self._call("select", [selector, *values], "list:string")

    async def tap(self, selector: str) -> None:
        """``Page.tap``.

        .. code-block:: typescript

            tap(selector: string): Promise<void>
        """
        return await self._call("tap", [selector], "void")

    async def type(self, selector: str, text: str, options: Any | None = None) -> None:
        """``Page.type``.

        .. code-block:: typescript

            type(selector: string, text: string, options?: Readonly<KeyboardTypeOptions>): Promise<void>
        """
        return await self._call("type", [selector, text, _opt(options)], "void")

    async def wait_for_selector(self, selector: str, options: Any | None = None) -> ElementHandle | None:
        """``Page.waitForSelector``.

        .. code-block:: typescript

            waitForSelector<Selector extends string>(selector: Selector, options?: WaitForSelectorOptions): Promise<ElementHandle<NodeFor<Selector>> | null>
        """
        return await self._call("waitForSelector", [selector, _opt(options)], "handle:ElementHandle?")

    async def wait_for_function(self, page_function: str | JsFunction, options: Any | None = None, *args: Any) -> JSHandle:
        """``Page.waitForFunction``.

        .. code-block:: typescript

            waitForFunction<Params extends unknown[], Func extends EvaluateFunc<Params> = EvaluateFunc<Params>>(pageFunction: Func | string, options?: FrameWaitForFunctionOptions, ...args: Params ): Promise<HandleFor<Awaited<ReturnType<Func>>>>
        """
        return await self._call("waitForFunction", [page_function, _opt(options), *args], "handle:JSHandle")

    async def wait_for_device_prompt(self, options: Any | None = None) -> DeviceRequestPrompt:
        """``Page.waitForDevicePrompt``.

        .. code-block:: typescript

            waitForDevicePrompt(options?: WaitTimeoutOptions): Promise<DeviceRequestPrompt>
        """
        return await self._call("waitForDevicePrompt", [_opt(options)], "handle:DeviceRequestPrompt")

    async def resize(self, params: Any) -> None:
        """``Page.resize``.

        .. code-block:: typescript

            resize(params: { contentWidth: number; contentHeight: number; }): Promise<void>
        """
        return await self._call("resize", [params], "void")

    async def window_id(self) -> str:
        """``Page.windowId``.

        .. code-block:: typescript

            windowId(): Promise<WindowId>
        """
        return await self._call("windowId", [], "string")

    async def open_dev_tools(self) -> Page:
        """``Page.openDevTools``.

        .. code-block:: typescript

            openDevTools(): Promise<Page>
        """
        return await self._call("openDevTools", [], "handle:Page")

    async def has_dev_tools(self) -> bool:
        """``Page.hasDevTools``.

        .. code-block:: typescript

            hasDevTools(): Promise<boolean>
        """
        return await self._call("hasDevTools", [], "boolean")

    async def bluetooth(self) -> BluetoothEmulation:
        """``Page.bluetooth``.

        .. code-block:: typescript

            get bluetooth(): BluetoothEmulation
        """
        return await self._get("bluetooth", "handle:BluetoothEmulation")

    async def trigger_extension_action(self, extension: Extension) -> None:
        """``Page.triggerExtensionAction``.

        .. code-block:: typescript

            triggerExtensionAction(extension: Extension): Promise<void>
        """
        return await self._call("triggerExtensionAction", [extension], "void")

    async def extension_realms(self) -> list[Realm]:
        """``Page.extensionRealms``.

        .. code-block:: typescript

            extensionRealms(): Realm[]
        """
        return await self._call("extensionRealms", [], "list:handle:Realm")
