# @generated by scripts/generate-puppeteer-bindings.mjs from
# rust/protocol/puppeteer/api.json. Do not edit by hand.
# mypy: disable-error-code="override"
"""Puppeteer's ``ProtocolError`` (puppeteer-core 25.10.0)."""

from __future__ import annotations

from .puppeteer_error import PuppeteerError


class ProtocolError(PuppeteerError):
    """Puppeteer's ``ProtocolError``, a remote object served by ``serve --stdio``."""

    TYPE = "ProtocolError"

    async def code(self) -> float | None:
        """``ProtocolError.code``.

        .. code-block:: typescript

            get code(): number | undefined
        """
        return await self._get("code", "number?")

    async def original_message(self) -> str:
        """``ProtocolError.originalMessage``.

        .. code-block:: typescript

            get originalMessage(): string
        """
        return await self._get("originalMessage", "string")
