# @generated by scripts/generate-puppeteer-bindings.mjs from
# rust/protocol/puppeteer/api.json. Do not edit by hand.
# mypy: disable-error-code="override"
"""Puppeteer's ``Puppeteer`` (puppeteer-core 25.12.0)."""

from __future__ import annotations

from typing import TYPE_CHECKING, Any

from ..bridge import RemoteObject

if TYPE_CHECKING:
    from .browser import Browser


class Puppeteer(RemoteObject):
    """Puppeteer's ``Puppeteer``, a remote object served by ``serve --stdio``."""

    TYPE = "Puppeteer"

    async def connect(self, options: Any) -> Browser:
        """``Puppeteer.connect``.

        .. code-block:: typescript

            connect(options: ConnectOptions): Promise<Browser>
        """
        return await self._call("connect", [options], "handle:Browser")
