# @generated by scripts/generate-puppeteer-bindings.mjs from
# rust/protocol/puppeteer/api.json. Do not edit by hand.
# mypy: disable-error-code="override"
"""Puppeteer's ``PuppeteerNode`` (puppeteer-core 25.12.0)."""

from __future__ import annotations

from typing import TYPE_CHECKING, Any

from ..bridge import _opt
from .puppeteer import Puppeteer

if TYPE_CHECKING:
    from .browser import Browser


class PuppeteerNode(Puppeteer):
    """Puppeteer's ``PuppeteerNode``, a remote object served by ``serve --stdio``."""

    TYPE = "PuppeteerNode"

    async def connect(self, options: Any) -> Browser:
        """``PuppeteerNode.connect``.

        .. code-block:: typescript

            connect(options: ConnectOptions): Promise<Browser>
        """
        return await self._call("connect", [options], "handle:Browser")

    async def launch(self, options: Any | None = None) -> Browser:
        """``PuppeteerNode.launch``.

        .. code-block:: typescript

            launch(options?: LaunchOptions): Promise<Browser>
        """
        return await self._call("launch", [_opt(options)], "handle:Browser")

    async def executable_path(self, channel: Any | None = None) -> str:
        """``PuppeteerNode.executablePath``.

        .. code-block:: typescript

            executablePath(channel: ChromeReleaseChannel): Promise<string>
            executablePath(options: LaunchOptions): Promise<string>
            executablePath(): Promise<string>
        """
        return await self._call("executablePath", [_opt(channel)], "string")

    async def last_launched_browser(self) -> str:
        """``PuppeteerNode.lastLaunchedBrowser``.

        .. code-block:: typescript

            lastLaunchedBrowser(): Promise<SupportedBrowser>
        """
        return await self._call("lastLaunchedBrowser", [], "string")

    async def default_browser(self) -> str:
        """``PuppeteerNode.defaultBrowser``.

        .. code-block:: typescript

            defaultBrowser(): Promise<SupportedBrowser>
        """
        return await self._call("defaultBrowser", [], "string")

    async def default_args(self, options: Any | None = None) -> list[str]:
        """``PuppeteerNode.defaultArgs``.

        .. code-block:: typescript

            defaultArgs(options?: LaunchOptions): Promise<string[]>
        """
        return await self._call("defaultArgs", [_opt(options)], "list:string")

    async def trim_cache(self) -> None:
        """``PuppeteerNode.trimCache``.

        .. code-block:: typescript

            trimCache(): Promise<void>
        """
        return await self._call("trimCache", [], "void")

    async def set_follow_symlinks(self, follow_symlinks: bool) -> None:
        """``PuppeteerNode.setFollowSymlinks``.

        .. code-block:: typescript

            setFollowSymlinks(followSymlinks: boolean): void
        """
        return await self._call("setFollowSymlinks", [follow_symlinks], "void")
