# @generated by scripts/generate-puppeteer-bindings.mjs from
# rust/protocol/puppeteer/api.json. Do not edit by hand.
# mypy: disable-error-code="override"
"""Puppeteer's ``ScreenRecording`` (puppeteer-core 25.12.0)."""

from __future__ import annotations

from typing import Any

from ..bridge import RemoteObject


class ScreenRecording(RemoteObject):
    """Puppeteer's ``ScreenRecording``, a remote object served by ``serve --stdio``."""

    TYPE = "ScreenRecording"

    async def pipe(self, destination: Any) -> Any:
        """``ScreenRecording.pipe``.

        .. code-block:: typescript

            pipe<T extends WritableStream<Uint8Array>>(destination: T): Promise<void>
            pipe<T extends WritableDestination>(destination: T): T
        """
        return await self._call("pipe", [destination], "json")

    async def stop(self) -> None:
        """``ScreenRecording.stop``.

        .. code-block:: typescript

            stop(): Promise<void>
        """
        return await self._call("stop", [], "void")
