# @generated by scripts/generate-puppeteer-bindings.mjs from
# rust/protocol/puppeteer/api.json. Do not edit by hand.
# mypy: disable-error-code="override"
"""Puppeteer's ``SecurityDetails`` (puppeteer-core 25.10.0)."""

from __future__ import annotations

from ..bridge import RemoteObject


class SecurityDetails(RemoteObject):
    """Puppeteer's ``SecurityDetails``, a remote object served by ``serve --stdio``."""

    TYPE = "SecurityDetails"

    async def issuer(self) -> str:
        """``SecurityDetails.issuer``.

        .. code-block:: typescript

            issuer(): string
        """
        return await self._call("issuer", [], "string")

    async def valid_from(self) -> float:
        """``SecurityDetails.validFrom``.

        .. code-block:: typescript

            validFrom(): number
        """
        return await self._call("validFrom", [], "number")

    async def valid_to(self) -> float:
        """``SecurityDetails.validTo``.

        .. code-block:: typescript

            validTo(): number
        """
        return await self._call("validTo", [], "number")

    async def protocol(self) -> str:
        """``SecurityDetails.protocol``.

        .. code-block:: typescript

            protocol(): string
        """
        return await self._call("protocol", [], "string")

    async def subject_name(self) -> str:
        """``SecurityDetails.subjectName``.

        .. code-block:: typescript

            subjectName(): string
        """
        return await self._call("subjectName", [], "string")

    async def subject_alternative_names(self) -> list[str]:
        """``SecurityDetails.subjectAlternativeNames``.

        .. code-block:: typescript

            subjectAlternativeNames(): string[]
        """
        return await self._call("subjectAlternativeNames", [], "list:string")
