# @generated by scripts/generate-puppeteer-bindings.mjs from
# rust/protocol/puppeteer/api.json. Do not edit by hand.
# mypy: disable-error-code="override"
"""Puppeteer's ``SerializedAXNode`` (puppeteer-core 25.10.0)."""

from __future__ import annotations

from typing import TYPE_CHECKING

from ..bridge import RemoteObject

if TYPE_CHECKING:
    from .element_handle import ElementHandle


class SerializedAXNode(RemoteObject):
    """Puppeteer's ``SerializedAXNode``, a remote object served by ``serve --stdio``."""

    TYPE = "SerializedAXNode"

    async def element_handle(self) -> ElementHandle | None:
        """``SerializedAXNode.elementHandle``.

        .. code-block:: typescript

            elementHandle(): Promise<ElementHandle | null>
        """
        return await self._call("elementHandle", [], "handle:ElementHandle?")
