# @generated by scripts/generate-puppeteer-bindings.mjs from
# rust/protocol/puppeteer/api.json. Do not edit by hand.
# mypy: disable-error-code="override"
"""Puppeteer's ``WebMCPTool`` (puppeteer-core 25.12.0)."""

from __future__ import annotations

from typing import TYPE_CHECKING, Any

from ..bridge import _opt
from .event_emitter import EventEmitter

if TYPE_CHECKING:
    from .element_handle import ElementHandle


class WebMCPTool(EventEmitter):
    """Puppeteer's ``WebMCPTool``, a remote object served by ``serve --stdio``."""

    TYPE = "WebMCPTool"

    async def form_element(self) -> ElementHandle | None:
        """``WebMCPTool.formElement``.

        .. code-block:: typescript

            get formElement(): Promise<ElementHandle<HTMLFormElement> | undefined>
        """
        return await self._get("formElement", "handle:ElementHandle?")

    async def execute(self, input: Any | None = None, options: Any | None = None) -> Any:
        """``WebMCPTool.execute``.

        .. code-block:: typescript

            execute(input?: object, options?: WebMCPToolExecuteOptions): Promise<WebMCPToolCallResult>
        """
        return await self._call("execute", [_opt(input), _opt(options)], "json")
