# @generated by scripts/generate-puppeteer-bindings.mjs from
# rust/protocol/puppeteer/api.json. Do not edit by hand.
# mypy: disable-error-code="override"
"""Puppeteer's ``WritableDestination`` (puppeteer-core 25.10.0)."""

from __future__ import annotations

from typing import Any

from ..bridge import JsFunction, RemoteObject


class WritableDestination(RemoteObject):
    """Puppeteer's ``WritableDestination``, a remote object served by ``serve --stdio``."""

    TYPE = "WritableDestination"

    async def write(self, chunk: bytes) -> bool:
        """``WritableDestination.write``.

        .. code-block:: typescript

            write(chunk: Uint8Array): boolean
        """
        return await self._call("write", [chunk], "boolean")

    async def end(self) -> Any:
        """``WritableDestination.end``.

        .. code-block:: typescript

            end(): unknown
        """
        return await self._call("end", [], "json")

    async def once(self, event: str, cb: str | JsFunction) -> Any:
        """``WritableDestination.once``.

        .. code-block:: typescript

            once?(event: string, cb: (arg?: unknown) => void): unknown
        """
        return await self._call("once", [event, cb], "json")
