// @generated by scripts/generate-puppeteer-bindings.mjs from
// rust/protocol/puppeteer/api.json. Do not edit by hand.

#![allow(clippy::all, missing_docs, unused_imports, non_snake_case)]

use serde_json::Value;

use super::*;
use crate::puppeteer::bridge::{binary, remote_type, BridgeError, JsFunction, Remote};

remote_type!(
    /// Puppeteer's `Accessibility` (puppeteer-core 25.12.0), a remote object
    /// served by `browser-commander serve --stdio`.
    Accessibility
);

impl Accessibility {
    /// `Accessibility.snapshot`
    ///
    /// ```text
    /// snapshot(options?: SnapshotOptions): Promise<SerializedAXNode | null>
    /// ```
    pub async fn snapshot(&self, options: Option<Value>) -> Result<Option<Value>, BridgeError> {
        self.remote.call("snapshot", vec![options]).await
    }
}
