// @generated by scripts/generate-puppeteer-bindings.mjs from
// rust/protocol/puppeteer/api.json. Do not edit by hand.

#![allow(clippy::all, missing_docs, unused_imports, non_snake_case)]

use serde_json::Value;

use super::*;
use crate::puppeteer::bridge::{binary, remote_type, BridgeError, JsFunction, Remote};

remote_type!(
    /// Puppeteer's `ConnectionTransport` (puppeteer-core 25.10.0), a remote object
    /// served by `browser-commander serve --stdio`.
    ConnectionTransport
);

impl ConnectionTransport {
    /// `ConnectionTransport.send`
    ///
    /// ```text
    /// send(message: string): void
    /// ```
    pub async fn send(&self, message: &str) -> Result<(), BridgeError> {
        self.remote.call("send", vec![Some(Value::from(message))]).await
    }

    /// `ConnectionTransport.close`
    ///
    /// ```text
    /// close(): void
    /// ```
    pub async fn close(&self) -> Result<(), BridgeError> {
        self.remote.call("close", vec![]).await
    }
}
