// @generated by scripts/generate-puppeteer-bindings.mjs from
// rust/protocol/puppeteer/api.json. Do not edit by hand.

#![allow(clippy::all, missing_docs, unused_imports, non_snake_case)]

use serde_json::Value;

use super::*;
use crate::puppeteer::bridge::{binary, remote_type, BridgeError, JsFunction, Remote};

remote_type!(
    /// Puppeteer's `CSSCoverage` (puppeteer-core 25.10.0), a remote object
    /// served by `browser-commander serve --stdio`.
    CSSCoverage
);

impl CSSCoverage {
    /// `CSSCoverage.start`
    ///
    /// ```text
    /// start(options?: {resetOnNavigation?: boolean}): Promise<void>
    /// ```
    pub async fn start(&self, options: Option<Value>) -> Result<(), BridgeError> {
        self.remote.call("start", vec![options]).await
    }

    /// `CSSCoverage.stop`
    ///
    /// ```text
    /// stop(): Promise<CoverageEntry[]>
    /// ```
    pub async fn stop(&self) -> Result<Vec<Value>, BridgeError> {
        self.remote.call("stop", vec![]).await
    }
}
