// @generated by scripts/generate-puppeteer-bindings.mjs from
// rust/protocol/puppeteer/api.json. Do not edit by hand.

//! Typed wrappers of Puppeteer's API, generated from the declaration file
//! that puppeteer-core ships.
//!
//! 47 types and 490 methods and getters, each a typed
//! `handle.call` or `handle.get` over [`crate::puppeteer::bridge`].

/// puppeteer-core release the wrappers were generated from.
pub const PUPPETEER_VERSION: &str = "25.10.0";

mod accessibility;
mod bluetooth_emulation;
mod browser;
mod browser_context;
mod browser_launcher;
mod cdp_session;
mod common_event_emitter;
mod connection;
mod connection_closed_error;
mod connection_transport;
mod console_message;
mod coverage;
mod css_coverage;
mod device_request_prompt;
mod dialog;
mod element_handle;
mod event_emitter;
mod extension;
mod extension_transport;
mod file_chooser;
mod frame;
mod http_request;
mod http_response;
mod js_coverage;
mod js_handle;
mod keyboard;
mod locator;
mod mouse;
mod moveable;
mod page;
mod page_2;
mod protocol_error;
mod puppeteer;
mod puppeteer_error;
mod puppeteer_node;
mod realm;
mod screen_recorder;
mod screen_recording;
mod security_details;
mod serialized_ax_node;
mod target;
mod touch_handle;
mod touchscreen;
mod tracing;
mod web_mcp;
mod web_mcp_tool;
mod web_worker;
mod writable_destination;

pub use accessibility::*;
pub use bluetooth_emulation::*;
pub use browser::*;
pub use browser_context::*;
pub use browser_launcher::*;
pub use cdp_session::*;
pub use common_event_emitter::*;
pub use connection::*;
pub use connection_closed_error::*;
pub use connection_transport::*;
pub use console_message::*;
pub use coverage::*;
pub use css_coverage::*;
pub use device_request_prompt::*;
pub use dialog::*;
pub use element_handle::*;
pub use event_emitter::*;
pub use extension::*;
pub use extension_transport::*;
pub use file_chooser::*;
pub use frame::*;
pub use http_request::*;
pub use http_response::*;
pub use js_coverage::*;
pub use js_handle::*;
pub use keyboard::*;
pub use locator::*;
pub use mouse::*;
pub use moveable::*;
pub use page::*;
pub use protocol_error::*;
pub use puppeteer::*;
pub use puppeteer_error::*;
pub use puppeteer_node::*;
pub use realm::*;
pub use screen_recorder::*;
pub use screen_recording::*;
pub use security_details::*;
pub use serialized_ax_node::*;
pub use target::*;
pub use touch_handle::*;
pub use touchscreen::*;
pub use tracing::*;
pub use web_mcp::*;
pub use web_mcp_tool::*;
pub use web_worker::*;
pub use writable_destination::*;
