// @generated by scripts/generate-puppeteer-bindings.mjs from
// rust/protocol/puppeteer/api.json. Do not edit by hand.

#![allow(clippy::all, missing_docs, unused_imports, non_snake_case)]

use serde_json::Value;

use super::*;
use crate::puppeteer::bridge::{binary, remote_type, BridgeError, JsFunction, Remote};

remote_type!(
    /// Puppeteer's `Puppeteer` (puppeteer-core 25.12.0), a remote object
    /// served by `browser-commander serve --stdio`.
    Puppeteer
);

impl Puppeteer {
    /// `Puppeteer.connect`
    ///
    /// ```text
    /// connect(options: ConnectOptions): Promise<Browser>
    /// ```
    pub async fn connect(&self, options: Value) -> Result<Browser, BridgeError> {
        self.remote.call("connect", vec![Some(options)]).await
    }
}
