// @generated by scripts/generate-puppeteer-bindings.mjs from
// rust/protocol/puppeteer/api.json. Do not edit by hand.

#![allow(clippy::all, missing_docs, unused_imports, non_snake_case)]

use serde_json::Value;

use super::*;
use crate::puppeteer::bridge::{binary, remote_type, BridgeError, JsFunction, Remote};

remote_type!(
    /// Puppeteer's `ScreenRecorder` (puppeteer-core 25.12.0), a remote object
    /// served by `browser-commander serve --stdio`.
    ScreenRecorder
);

impl ScreenRecorder {
    /// `ScreenRecorder.stop`
    ///
    /// ```text
    /// stop(): Promise<void>
    /// ```
    pub async fn stop(&self) -> Result<(), BridgeError> {
        self.remote.call("stop", vec![]).await
    }
}
