// @generated by scripts/generate-puppeteer-bindings.mjs from
// rust/protocol/puppeteer/api.json. Do not edit by hand.

#![allow(clippy::all, missing_docs, unused_imports, non_snake_case)]

use serde_json::Value;

use super::*;
use crate::puppeteer::bridge::{binary, remote_type, BridgeError, JsFunction, Remote};

remote_type!(
    /// Puppeteer's `TouchHandle` (puppeteer-core 25.10.0), a remote object
    /// served by `browser-commander serve --stdio`.
    TouchHandle
);

impl TouchHandle {
    /// `TouchHandle.move`
    ///
    /// ```text
    /// move(x: number, y: number): Promise<void>
    /// ```
    pub async fn r#move(&self, x: f64, y: f64) -> Result<(), BridgeError> {
        self.remote.call("move", vec![Some(Value::from(x)), Some(Value::from(y))]).await
    }

    /// `TouchHandle.end`
    ///
    /// ```text
    /// end(): Promise<void>
    /// ```
    pub async fn end(&self) -> Result<(), BridgeError> {
        self.remote.call("end", vec![]).await
    }
}
