"""
Browser Commander - Universal browser automation library for Python.

Supports both Playwright and Selenium with a unified API.
All functions use options dictionaries for easy maintenance.

Key features:
- Automatic network request tracking
- Navigation-aware operations (wait for page ready after navigations)
- Event-based page lifecycle management
- Session management for per-page automation logic
"""

from __future__ import annotations

from browser_commander.exports import (
    # Core utilities
    ALL_DATA_CLASSES,
    AUTOMATION_CONTROLLED_OFF_ARG,
    AUTOMATION_CONTROLLED_TRIGGERS,
    CHROME_ARGS,
    FINGERPRINT_FIELD_MECHANISMS,
    FINGERPRINT_LIMITATIONS,
    FINGERPRINT_PRESET_NAMES,
    LAUNCH_MODES,
    LAUNCH_RESTRICTION_PRESETS,
    LAUNCH_RESTRICTIONS,
    LONG_LIVED_REQUEST_PATTERNS,
    PLAYWRIGHT_HEADLESS_POINTER_ARG,
    PLAYWRIGHT_SOFTWARE_WEBGL_ARG,
    TIMING,
    ActionStoppedError,
    AppliedFingerprint,
    BrowserCookieCacheOptions,
    BrowserCookieReadOptions,
    BrowserProfile,
    CdpCommand,
    ClickActionability,
    ClickActivation,
    ClickEffect,
    ClickResult,
    ClickScroll,
    ClickStatus,
    ClickVerificationResult,
    CommandError,
    ConnectOptions,
    CookieSource,
    Deadline,
    # Engine adapter
    EngineAdapter,
    EngineType,
    EvaluateResult,
    ExtensionRelay,
    FillResult,
    FillVerificationResult,
    GotoResult,
    ImportSource,
    LaunchOptions,
    LaunchResult,
    ManagedProcess,
    NavigationManager,
    NavigationVerificationResult,
    # Core components
    NetworkTracker,
    # Page trigger system
    PageTriggerManager,
    PlaywrightAdapter,
    PortRaceError,
    ReadinessCheck,
    ReadinessResult,
    ReadinessStatus,
    RealBrowserOptions,
    RealBrowserResult,
    RelayAddress,
    RelayEvent,
    RelayExtension,
    RelayOptions,
    RelaySession,
    RelayTab,
    ScrollConstraintError,
    ScrollResult,
    ScrollVerificationResult,
    SeleniumAdapter,
    SeleniumLocatorWrapper,
    SeleniumTextSelector,
    SnapshotOptions,
    WaitAfterActionResult,
    WaitResult,
    all_conditions,
    any_condition,
    apply_automation_parity_args,
    apply_fingerprint,
    assert_fixed_debugging_port,
    attach_via_extension,
    browser_environment,
    build_cdp_emulation_commands,
    build_fingerprint_init_script,
    build_init_script_config,
    build_open_command,
    build_real_browser_args,
    capture_pre_click_state,
    check_and_clear_flag,
    # Fill interactions
    check_if_element_empty,
    classify_differences,
    click_button,
    # Click interactions
    click_element,
    compare_command_lines,
    connect_browser,
    count,
    create_cdp_session,
    create_engine_adapter,
    create_fingerprint_preset,
    create_logger,
    # Element locators
    create_playwright_locator,
    create_temporary_user_data_dir,
    default_click_verification,
    default_fill_verification,
    default_navigation_verification,
    default_scroll_verification,
    derive_user_agent_data,
    detect_automation_controlled_triggers,
    detect_engine,
    disables_automation_controlled,
    dom_stable_for,
    emulate_media,
    evaluate,
    extension_directory,
    fill_text_area,
    find_by_text,
    find_fingerprint_limitation,
    find_toggle_button,
    get_attribute,
    get_input_value,
    get_locator_or_element,
    get_url,
    goto,
    input_value,
    install_click_listener,
    is_action_stopped_error,
    is_enabled,
    is_long_lived_request,
    is_navigation_error,
    is_timeout_error,
    is_verbose_enabled,
    # Element visibility
    is_visible,
    launch_and_connect_real_browser,
    launch_browser,
    launch_real_browser,
    launch_snapshot,
    list_browser_profiles,
    list_cookie_sources,
    load_storage_state,
    locator,
    log_element_info,
    make_url_condition,
    measure_parity,
    merge_feature_switches,
    migrate_profile,
    needs_scrolling,
    network_idle_for,
    normalize_selector,
    not_condition,
    open_in_user_browser,
    parity_ignored_default_args,
    parse_switches,
    perform_fill,
    pick_foreground_page,
    predicate,
    prepare_user_data_dir,
    # Element selectors
    query_selector,
    query_selector_all,
    read_browser_cookies,
    read_browser_version_page,
    relevant_fingerprint_limitations,
    remove_user_data_dir,
    reserve_loopback_port,
    resolve_fingerprint_profile,
    resolve_import_source,
    resolve_launch_executable,
    resolve_restrictions,
    run_command,
    run_readiness_checks,
    safe_evaluate,
    safe_operation,
    save_storage_state,
    # Scroll interactions
    scroll_into_view,
    scroll_into_view_if_needed,
    snapshot_user_data_dir,
    stable_check,
    start_process,
    # Element content
    text_content,
    unfocus_address_bar,
    url_stable_for,
    validate_open_url,
    verify_click,
    verify_fill,
    verify_navigation,
    verify_scroll,
    visible_images,
    # Utilities
    wait,
    wait_after_action,
    wait_for_locator_or_element,
    wait_for_navigation,
    wait_for_page_ready,
    wait_for_selector,
    # High-level
    wait_for_url_condition,
    wait_for_url_stabilization,
    wait_for_visible,
    with_navigation_safety,
    with_text_selector_support,
)
from browser_commander.factory import BrowserCommander, make_browser_commander

__version__ = "0.1.0"
__all__ = [
    # Core utilities
    "ALL_DATA_CLASSES",
    "AUTOMATION_CONTROLLED_OFF_ARG",
    "AUTOMATION_CONTROLLED_TRIGGERS",
    "CHROME_ARGS",
    "FINGERPRINT_FIELD_MECHANISMS",
    "FINGERPRINT_LIMITATIONS",
    "FINGERPRINT_PRESET_NAMES",
    "LAUNCH_MODES",
    "LAUNCH_RESTRICTIONS",
    "LAUNCH_RESTRICTION_PRESETS",
    "LONG_LIVED_REQUEST_PATTERNS",
    "PLAYWRIGHT_HEADLESS_POINTER_ARG",
    "PLAYWRIGHT_SOFTWARE_WEBGL_ARG",
    "TIMING",
    "ActionStoppedError",
    "AppliedFingerprint",
    # Factory
    "BrowserCommander",
    "BrowserCookieCacheOptions",
    "BrowserCookieReadOptions",
    "BrowserProfile",
    "CdpCommand",
    "ClickActionability",
    "ClickActivation",
    "ClickEffect",
    "ClickResult",
    "ClickScroll",
    "ClickStatus",
    "ClickVerificationResult",
    "CommandError",
    "ConnectOptions",
    "CookieSource",
    "Deadline",
    # Engine adapter
    "EngineAdapter",
    "EngineType",
    "EvaluateResult",
    "ExtensionRelay",
    "FillResult",
    "FillVerificationResult",
    "GotoResult",
    "ImportSource",
    "LaunchOptions",
    "LaunchResult",
    "ManagedProcess",
    "NavigationManager",
    "NavigationVerificationResult",
    # Core components
    "NetworkTracker",
    # Page trigger system
    "PageTriggerManager",
    "PlaywrightAdapter",
    "PortRaceError",
    "ReadinessCheck",
    "ReadinessResult",
    "ReadinessStatus",
    "RealBrowserOptions",
    "RealBrowserResult",
    "RelayAddress",
    "RelayEvent",
    "RelayExtension",
    "RelayOptions",
    "RelaySession",
    "RelayTab",
    "ScrollConstraintError",
    "ScrollResult",
    "ScrollVerificationResult",
    "SeleniumAdapter",
    "SeleniumLocatorWrapper",
    "SeleniumTextSelector",
    "SnapshotOptions",
    "WaitAfterActionResult",
    "WaitResult",
    "all_conditions",
    "any_condition",
    "apply_automation_parity_args",
    "apply_fingerprint",
    "assert_fixed_debugging_port",
    "attach_via_extension",
    "browser_environment",
    "build_cdp_emulation_commands",
    "build_fingerprint_init_script",
    "build_init_script_config",
    "build_open_command",
    "build_real_browser_args",
    "capture_pre_click_state",
    "check_and_clear_flag",
    # Fill interactions
    "check_if_element_empty",
    "classify_differences",
    "click_button",
    # Click interactions
    "click_element",
    "compare_command_lines",
    "connect_browser",
    "count",
    "create_cdp_session",
    "create_engine_adapter",
    "create_fingerprint_preset",
    "create_logger",
    # Element locators
    "create_playwright_locator",
    "create_temporary_user_data_dir",
    "default_click_verification",
    "default_fill_verification",
    "default_navigation_verification",
    "default_scroll_verification",
    "derive_user_agent_data",
    "detect_automation_controlled_triggers",
    "detect_engine",
    "disables_automation_controlled",
    "dom_stable_for",
    "emulate_media",
    "evaluate",
    "extension_directory",
    "fill_text_area",
    "find_by_text",
    "find_fingerprint_limitation",
    "find_toggle_button",
    "get_attribute",
    "get_input_value",
    "get_locator_or_element",
    "get_url",
    "goto",
    "input_value",
    "install_click_listener",
    "is_action_stopped_error",
    "is_enabled",
    "is_long_lived_request",
    "is_navigation_error",
    "is_timeout_error",
    "is_verbose_enabled",
    # Element visibility
    "is_visible",
    "launch_and_connect_real_browser",
    "launch_browser",
    "launch_real_browser",
    "launch_snapshot",
    "list_browser_profiles",
    "list_cookie_sources",
    "load_storage_state",
    "locator",
    "log_element_info",
    "make_browser_commander",
    "make_url_condition",
    "measure_parity",
    "merge_feature_switches",
    "migrate_profile",
    "needs_scrolling",
    "network_idle_for",
    "normalize_selector",
    "not_condition",
    "open_in_user_browser",
    "parity_ignored_default_args",
    "parse_switches",
    "perform_fill",
    "pick_foreground_page",
    "predicate",
    "prepare_user_data_dir",
    # Element selectors
    "query_selector",
    "query_selector_all",
    "read_browser_cookies",
    "read_browser_version_page",
    "relevant_fingerprint_limitations",
    "remove_user_data_dir",
    "reserve_loopback_port",
    "resolve_fingerprint_profile",
    "resolve_import_source",
    "resolve_launch_executable",
    "resolve_restrictions",
    "run_command",
    "run_readiness_checks",
    "safe_evaluate",
    "safe_operation",
    "save_storage_state",
    # Scroll interactions
    "scroll_into_view",
    "scroll_into_view_if_needed",
    "snapshot_user_data_dir",
    "stable_check",
    "start_process",
    # Element content
    "text_content",
    "unfocus_address_bar",
    "url_stable_for",
    "validate_open_url",
    "verify_click",
    "verify_fill",
    "verify_navigation",
    "verify_scroll",
    "visible_images",
    # Utilities
    "wait",
    "wait_after_action",
    "wait_for_locator_or_element",
    "wait_for_navigation",
    "wait_for_page_ready",
    "wait_for_selector",
    # High-level
    "wait_for_url_condition",
    "wait_for_url_stabilization",
    "wait_for_visible",
    "with_navigation_safety",
    "with_text_selector_support",
]
