/**
 * Coverage of the typed Rust and Python Puppeteer wrappers (issue #108).
 *
 * `rust/src/puppeteer/api/` and `python/src/browser_commander/puppeteer/api/`
 * are generated by `scripts/generate-puppeteer-bindings.mjs` from
 * `rust/protocol/puppeteer/api.json`, which `scripts/puppeteer-api.mjs`
 * extracts from puppeteer-core's `lib/types.d.ts`. These tests fail when:
 *
 * - the committed wrappers differ from what the generator writes;
 * - the committed manifest differs from the installed puppeteer-core,
 *   including its version (a mismatch fails rather than skips);
 * - a public method or getter declared in `lib/types.d.ts` (own or inherited)
 *   has no typed entry point in Rust or Python.
 */

import assert from 'node:assert/strict';
import * as fs from 'node:fs';
import path from 'node:path';
import { describe, it } from 'node:test';
import { pathToFileURL } from 'node:url';

import { puppeteerDeclarations } from '../helpers/declared-api.js';
import { repoPath } from '../helpers/repo.js';

const generator = await import(
  pathToFileURL(repoPath('scripts/generate-puppeteer-bindings.mjs'))
);
const extractor = await import(
  pathToFileURL(repoPath('scripts/puppeteer-api.mjs'))
);

const {
  MANIFEST_PATH,
  RUST_DIR,
  PYTHON_DIR,
  formatManifest,
  generatePuppeteerBindings,
  loadManifest,
  pythonMethodName,
  rustMethodName,
} = generator;

const manifest = loadManifest();
const types = new Map(manifest.types.map((type) => [type.name, type]));

function readDir(dir, extension) {
  return new Map(
    fs
      .readdirSync(dir)
      .filter((file) => file.endsWith(extension))
      .map((file) => [file, fs.readFileSync(path.join(dir, file), 'utf8')])
  );
}

/** The body of every `impl Name {` block, keyed by type name. */
function rustImpls(files) {
  const impls = new Map();
  for (const source of files.values()) {
    for (const match of source.matchAll(/^impl (\w+) \{\n([\s\S]*?)^\}/gmu)) {
      impls.set(match[1], (impls.get(match[1]) ?? '') + match[2]);
    }
  }
  return impls;
}

/** The body of every top-level `class Name(…):`, keyed by class name. */
function pythonClasses(files) {
  const classes = new Map();
  for (const source of files.values()) {
    for (const match of source.matchAll(
      /^class (\w+)\([^)]*\):\n([\s\S]*?)(?=^\S|(?![\s\S]))/gmu
    )) {
      classes.set(match[1], match[2]);
    }
  }
  return classes;
}

const rust = rustImpls(readDir(RUST_DIR, '.rs'));
const python = pythonClasses(readDir(PYTHON_DIR, '.py'));

/** Python inherits: a method is reachable when it or an ancestor defines it. */
function pythonHas(typeName, method) {
  const pattern = new RegExp(
    `^ {4}async def ${pythonMethodName(method)}\\(`,
    'mu'
  );
  for (let name = typeName; name; name = types.get(name)?.extends ?? null) {
    if (pattern.test(python.get(name) ?? '')) {
      return true;
    }
  }
  return false;
}

/** Rust has no inheritance: the method must be on the type's own `impl`. */
function rustHas(typeName, owner, method) {
  const doc = `/// \`${owner}.${method}\``;
  const name = rustMethodName(method);
  const body = rust.get(typeName) ?? '';
  return body.includes(doc) && body.includes(`pub async fn ${name}(`);
}

describe('Puppeteer bindings (Rust and Python)', () => {
  it('are what the generator writes from the committed manifest', () => {
    const generated = generatePuppeteerBindings(manifest);
    for (const [dir, files, extension] of [
      [RUST_DIR, generated.rust, '.rs'],
      [PYTHON_DIR, generated.python, '.py'],
    ]) {
      const committed = readDir(dir, extension);
      assert.deepEqual(
        [...committed.keys()].sort(),
        [...files.keys()].sort(),
        `${dir} has stale or missing files; run node scripts/generate-puppeteer-bindings.mjs`
      );
      for (const [file, text] of files) {
        assert.equal(
          committed.get(file),
          text,
          `${path.join(dir, file)} is out of date; run node scripts/generate-puppeteer-bindings.mjs`
        );
      }
    }
  });

  it('come from the installed puppeteer-core', (t) => {
    let installed;
    try {
      installed = extractor.installedPuppeteer();
    } catch {
      t.skip('puppeteer-core is not installed');
      return;
    }
    // A version mismatch is exactly the drift this test exists to catch (issue
    // #128: puppeteer-core was upgraded to 25.12.0 while the manifest stayed
    // at 25.10.0, and a skip here hid it), so it fails instead of skipping.
    assert.equal(
      manifest.version,
      installed.version,
      `puppeteer-core ${installed.version} is installed, the manifest is ${manifest.version}; ` +
        'run node scripts/generate-puppeteer-bindings.mjs --update-api'
    );
    const fresh = {
      package: 'puppeteer-core',
      version: installed.version,
      ...extractor.extractPuppeteerApi(installed.source),
    };
    assert.equal(
      fs.readFileSync(MANIFEST_PATH, 'utf8'),
      formatManifest(fresh),
      'run node scripts/generate-puppeteer-bindings.mjs --update-api'
    );
  });

  it('are read through virtual paths the TypeScript API can find on Windows', () => {
    // TypeScript 7's virtual file system matches file names as exact keys, and
    // the native compiler asks for them with forward slashes. Keys built with
    // path.join on Windows (`D:\a\…\tsconfig.json`) were never found, so the
    // project came back undefined (issue #128, run 37526767522).
    const paths = extractor.virtualProjectPaths(
      'D:\\a\\browser-commander\\browser-commander'
    );
    assert.deepEqual(paths, {
      cwd: 'D:/a/browser-commander/browser-commander/experiments/puppeteer-api-virtual',
      config:
        'D:/a/browser-commander/browser-commander/experiments/puppeteer-api-virtual/tsconfig.json',
      declaration:
        'D:/a/browser-commander/browser-commander/experiments/puppeteer-api-virtual/types.d.ts',
    });
  });

  it('give every declared Puppeteer method a typed entry point', () => {
    const missing = [];
    let checked = 0;
    for (const [typeName, methods] of puppeteerDeclarations()) {
      for (const method of methods) {
        checked += 1;
        const member = types
          .get(typeName)
          ?.methods.find((candidate) => candidate.name === method);
        if (!member) {
          missing.push(`${typeName}.${method}: not in the manifest`);
          continue;
        }
        if (!rustHas(typeName, member.owner, method)) {
          missing.push(`${typeName}.${method}: no Rust method`);
        }
        if (!pythonHas(typeName, method)) {
          missing.push(`${typeName}.${method}: no Python method`);
        }
      }
    }
    assert.deepEqual(missing, []);
    assert.ok(checked > 250, `only ${checked} declared methods were checked`);
  });

  it('give every manifest member, own or inherited, a typed entry point', () => {
    const missing = [];
    let members = 0;
    for (const type of manifest.types) {
      for (const member of type.methods) {
        members += 1;
        if (!rustHas(type.name, member.owner, member.name)) {
          missing.push(`Rust ${type.name}.${member.name}`);
        }
        if (!pythonHas(type.name, member.name)) {
          missing.push(`Python ${type.name}.${member.name}`);
        }
      }
    }
    assert.deepEqual(missing, []);
    assert.ok(types.size > 40, `only ${types.size} types`);
    assert.ok(members > 450, `only ${members} members`);
  });

  it('keep Python classes in the Puppeteer class hierarchy', () => {
    for (const type of manifest.types) {
      const source = fs.readFileSync(
        path.join(PYTHON_DIR, `${generator.snakeCase(type.name)}.py`),
        'utf8'
      );
      const parent =
        type.extends &&
        fs.existsSync(
          path.join(PYTHON_DIR, `${generator.snakeCase(type.extends)}.py`)
        );
      const base = parent ? type.extends : 'RemoteObject';
      assert.match(
        source,
        new RegExp(`^class ${type.name}\\(${base}\\):`, 'mu')
      );
    }
  });
});
