"""Puppeteer from Python, typed, over the JavaScript CLI's bridge (issue #108).

Puppeteer exists only for Node.js, so :class:`PuppeteerBridge` starts
``browser-commander serve --stdio`` and works with Puppeteer's objects as
remote handles. :mod:`browser_commander.puppeteer.api` is generated by
``scripts/generate-puppeteer-bindings.mjs`` from the declaration file that
puppeteer-core ships: one class per Puppeteer class or interface, with a typed
``async def`` for every method and getter.
"""

from __future__ import annotations

from browser_commander.puppeteer.api import *  # noqa: F403
from browser_commander.puppeteer.api import PUPPETEER_VERSION
from browser_commander.puppeteer.api import __all__ as _api_names
from browser_commander.puppeteer.bridge import (
    UNDEFINED,
    BridgeClient,
    BridgeClosedError,
    BridgeError,
    JsFunction,
    PuppeteerBridge,
    RemoteHandle,
    RemoteObject,
    Subscription,
)

__all__ = [
    "PUPPETEER_VERSION",
    "UNDEFINED",
    "BridgeClient",
    "BridgeClosedError",
    "BridgeError",
    "JsFunction",
    "PuppeteerBridge",
    "RemoteHandle",
    "RemoteObject",
    "Subscription",
    *_api_names,
]
